In [1]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah","Sakib"],
    "City": ["New York", "Los Angeles", "Newark", "Boston", "New Delhi", "Chicago", "New Orleans", "Houston","H Los Ang"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Marketing", "Finance", "HR", "HR"],
    "Salary": [50000, 60000, 55000, 70000, 52000, 58000, 62000, 51000,70000]
}

df = pd.DataFrame(data)

df

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
3    David       Boston         IT   70000
4      Eve    New Delhi         HR   52000
5    Frank      Chicago  Marketing   58000
6    Grace  New Orleans    Finance   62000
7   Hannah      Houston         HR   51000
8    Sakib    H Los Ang         HR   70000

In [2]:
df.loc[df['City'].str.contains("New")]

      Name         City Department  Salary
0    Alice     New York         HR   50000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000

In [4]:
df.loc[df['City'].str.contains("new",case = False)]

      Name         City Department  Salary
0    Alice     New York         HR   50000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000

In [6]:
df.loc[df['City'].str.contains(r"los", case = False)]

    Name         City Department  Salary
1    Bob  Los Angeles         IT   60000
8  Sakib    H Los Ang         HR   70000

In [7]:
df.loc[df['City'].str.contains(r"^los", case = False)]

  Name         City Department  Salary
1  Bob  Los Angeles         IT   60000

In [8]:
df.loc[df['City'].str.contains(r"rk$")]

      Name      City Department  Salary
0    Alice  New York         HR   50000
2  Charlie    Newark    Finance   55000

In [10]:
df.loc[df['Name'].str.contains(r"^[AEIOU]", case = False)]

    Name       City Department  Salary
0  Alice   New York         HR   50000
4    Eve  New Delhi         HR   52000

In [14]:
df.loc[df['City'].str.contains(r"^Los|New")]

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000

In [19]:
df = pd.read_csv('student_data.csv')
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Amena Islam,69.7,68.5,90.2,Completed,2024-01-24,Mr. Haque,Rangpur
1,PH1002,Kamal Akhter,65.9,71.8,87.1,Completed,2024-02-07,Ms. Salma,Mymensingh
2,PH1003,Tania Bhuiyan,77.5,75.8,90.6,In Progress,2024-01-25,Mr. Karim,Chattogram
3,PH1004,Sajid Hasan,89.7,84.5,NaN,In Progress,2024-06-28,Ms. Rina,Chattogram
4,PH1005,Quamrul Sarkar,89.0,66.6,72.7,Completed,2024-11-20,Mr. Karim,Rajshahi
...,...,...,...,...,...,...,...,...,...
95,PH1096,Zobair Hossain,77.4,69.5,95.9,Completed,2025-05-26,Ms. Rina,Sylhet
96,PH1097,Taslima Faruq,94.7,95.5,96.1,In Progress,2024-09-12,Mr. David,Barishal
97,PH1098,Wahiduzzaman Majumder,NaN,NaN,NaN,In Progress,2024-02-05,Mr. Haque,Barishal
98,PH1099,Sadia Paul,87.9,87.9,84.9,Completed,2024-01-09,Mr. David,Chattogram
99,PH1100,Firoz Khan,NaN,NaN,NaN,Not Started,2024-08-01,Ms. Salma,Chattogram

In [20]:
df['Country'] = 'Bangladesh'

In [21]:
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country
0,PH1001,Amena Islam,69.7,68.5,90.2,Completed,2024-01-24,Mr. Haque,Rangpur,Bangladesh
1,PH1002,Kamal Akhter,65.9,71.8,87.1,Completed,2024-02-07,Ms. Salma,Mymensingh,Bangladesh
2,PH1003,Tania Bhuiyan,77.5,75.8,90.6,In Progress,2024-01-25,Mr. Karim,Chattogram,Bangladesh
3,PH1004,Sajid Hasan,89.7,84.5,NaN,In Progress,2024-06-28,Ms. Rina,Chattogram,Bangladesh
4,PH1005,Quamrul Sarkar,89.0,66.6,72.7,Completed,2024-11-20,Mr. Karim,Rajshahi,Bangladesh

In [22]:
df['Total Marks'] = df['Data Structure Marks'] + df['Algorithm Marks'] + df['Python Marks']

In [23]:
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks
0,PH1001,Amena Islam,69.7,68.5,90.2,Completed,2024-01-24,Mr. Haque,Rangpur,Bangladesh,228.4
1,PH1002,Kamal Akhter,65.9,71.8,87.1,Completed,2024-02-07,Ms. Salma,Mymensingh,Bangladesh,224.8
2,PH1003,Tania Bhuiyan,77.5,75.8,90.6,In Progress,2024-01-25,Mr. Karim,Chattogram,Bangladesh,243.9
3,PH1004,Sajid Hasan,89.7,84.5,NaN,In Progress,2024-06-28,Ms. Rina,Chattogram,Bangladesh,NaN
4,PH1005,Quamrul Sarkar,89.0,66.6,72.7,Completed,2024-11-20,Mr. Karim,Rajshahi,Bangladesh,228.3

In [24]:
import numpy as np

In [26]:
df['A+ in DS'] = np.where(df['Data Structure Marks'] > 90, 'A+','A')

In [27]:
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS
0,PH1001,Amena Islam,69.7,68.5,90.2,Completed,2024-01-24,Mr. Haque,Rangpur,Bangladesh,228.4,A
1,PH1002,Kamal Akhter,65.9,71.8,87.1,Completed,2024-02-07,Ms. Salma,Mymensingh,Bangladesh,224.8,A
2,PH1003,Tania Bhuiyan,77.5,75.8,90.6,In Progress,2024-01-25,Mr. Karim,Chattogram,Bangladesh,243.9,A
3,PH1004,Sajid Hasan,89.7,84.5,NaN,In Progress,2024-06-28,Ms. Rina,Chattogram,Bangladesh,NaN,A
4,PH1005,Quamrul Sarkar,89.0,66.6,72.7,Completed,2024-11-20,Mr. Karim,Rajshahi,Bangladesh,228.3,A

In [28]:
df['Passes in DS'] = df['Data Structure Marks'] > 70
df.head(10)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passes in DS
0,PH1001,Amena Islam,69.7,68.5,90.2,Completed,2024-01-24,Mr. Haque,Rangpur,Bangladesh,228.4,A,False
1,PH1002,Kamal Akhter,65.9,71.8,87.1,Completed,2024-02-07,Ms. Salma,Mymensingh,Bangladesh,224.8,A,False
2,PH1003,Tania Bhuiyan,77.5,75.8,90.6,In Progress,2024-01-25,Mr. Karim,Chattogram,Bangladesh,243.9,A,True
3,PH1004,Sajid Hasan,89.7,84.5,NaN,In Progress,2024-06-28,Ms. Rina,Chattogram,Bangladesh,NaN,A,True
4,PH1005,Quamrul Sarkar,89.0,66.6,72.7,Completed,2024-11-20,Mr. Karim,Rajshahi,Bangladesh,228.3,A,True
5,PH1006,Tanvir Das,77.1,87.8,88.9,Completed,2024-05-15,Mr. Karim,Sylhet,Bangladesh,253.8,A,True
6,PH1007,Osman Mimi,96.5,88.4,72.5,Completed,2025-03-15,Mr. Karim,Rajshahi,Bangladesh,257.4,A+,True
7,PH1008,Kamal Talukder,97.1,94.8,75.7,Completed,2024-07-09,Ms. Rina,Mymensingh,Bangladesh,267.6,A+,True
8,PH1009,Faria Khatun,NaN,NaN,NaN,In Progress,2024-03-08,Mr. Haque,Rangpur,Bangladesh,NaN,A,False
9,PH1010,Rezaul Khan,66.6,68.7,86.3,Completed,2025-03-17,Ms. Rina,Chattogram,Bangladesh,221.6,A,False

In [29]:
df['First Name'] = df['FullName'].str.split(' ').str[0]
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passes in DS,First Name
0,PH1001,Amena Islam,69.7,68.5,90.2,Completed,2024-01-24,Mr. Haque,Rangpur,Bangladesh,228.4,A,False,Amena
1,PH1002,Kamal Akhter,65.9,71.8,87.1,Completed,2024-02-07,Ms. Salma,Mymensingh,Bangladesh,224.8,A,False,Kamal
2,PH1003,Tania Bhuiyan,77.5,75.8,90.6,In Progress,2024-01-25,Mr. Karim,Chattogram,Bangladesh,243.9,A,True,Tania
3,PH1004,Sajid Hasan,89.7,84.5,NaN,In Progress,2024-06-28,Ms. Rina,Chattogram,Bangladesh,NaN,A,True,Sajid
4,PH1005,Quamrul Sarkar,89.0,66.6,72.7,Completed,2024-11-20,Mr. Karim,Rajshahi,Bangladesh,228.3,A,True,Quamrul
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,PH1096,Zobair Hossain,77.4,69.5,95.9,Completed,2025-05-26,Ms. Rina,Sylhet,Bangladesh,242.8,A,True,Zobair
96,PH1097,Taslima Faruq,94.7,95.5,96.1,In Progress,2024-09-12,Mr. David,Barishal,Bangladesh,286.3,A+,True,Taslima
97,PH1098,Wahiduzzaman Majumder,NaN,NaN,NaN,In Progress,2024-02-05,Mr. Haque,Barishal,Bangladesh,NaN,A,False,Wahiduzzaman
98,PH1099,Sadia Paul,87.9,87.9,84.9,Completed,2024-01-09,Mr. David,Chattogram,Bangladesh,260.7,A,True,Sadia
99,PH1100,Firoz Khan,NaN,NaN,NaN,Not Started,2024-08-01,Ms. Salma,Chattogram,Bangladesh,NaN,A,False,Firoz

In [30]:
df.to_csv('new_data.csv')

In [31]:
df1 = pd.read_csv('new_data.csv')
df1

,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passes in DS,First Name
0,0,PH1001,Amena Islam,69.7,68.5,90.2,Completed,2024-01-24,Mr. Haque,Rangpur,Bangladesh,228.4,A,False,Amena
1,1,PH1002,Kamal Akhter,65.9,71.8,87.1,Completed,2024-02-07,Ms. Salma,Mymensingh,Bangladesh,224.8,A,False,Kamal
2,2,PH1003,Tania Bhuiyan,77.5,75.8,90.6,In Progress,2024-01-25,Mr. Karim,Chattogram,Bangladesh,243.9,A,True,Tania
3,3,PH1004,Sajid Hasan,89.7,84.5,NaN,In Progress,2024-06-28,Ms. Rina,Chattogram,Bangladesh,NaN,A,True,Sajid
4,4,PH1005,Quamrul Sarkar,89.0,66.6,72.7,Completed,2024-11-20,Mr. Karim,Rajshahi,Bangladesh,228.3,A,True,Quamrul
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,PH1096,Zobair Hossain,77.4,69.5,95.9,Completed,2025-05-26,Ms. Rina,Sylhet,Bangladesh,242.8,A,True,Zobair
96,96,PH1097,Taslima Faruq,94.7,95.5,96.1,In Progress,2024-09-12,Mr. David,Barishal,Bangladesh,286.3,A+,True,Taslima
97,97,PH1098,Wahiduzzaman Majumder,NaN,NaN,NaN,In Progress,2024-02-05,Mr. Haque,Barishal,Bangladesh,NaN,A,False,Wahiduzzaman
98,98,PH1099,Sadia Paul,87.9,87.9,84.9,Completed,2024-01-09,Mr. David,Chattogram,Bangladesh,260.7,A,True,Sadia
99,99,PH1100,Firoz Khan,NaN,NaN,NaN,Not Started,2024-08-01,Ms. Salma,Chattogram,Bangladesh,NaN,A,False,Firoz

In [32]:
df['FullName'].unique()

array(['Amena Islam', 'Kamal Akhter', 'Tania Bhuiyan', 'Sajid Hasan',
       'Quamrul Sarkar', 'Tanvir Das', 'Osman Mimi', 'Kamal Talukder',
       'Faria Khatun', 'Rezaul Khan', 'Fahmida Das', 'Gitika Bhuiyan',
       'Masud Hasan', 'Liton Akhter', 'Afsana Hawlader', 'Sinthia Nath',
       'Priya Ferdous', 'Tahmina Faruq', 'Golam Majumder', 'Babul Saha',
       'Sadia Mimi', 'Jahangir Sarkar', 'Mahmudul Hawlader', 'Ziaur Mimi',
       'Dilara Akter', 'Jahangir Hasan', 'Ismail Mondal', 'Urmi Sharma',
       'Rasel Ferdous', 'Nurul Barua', 'Sumon Sharma', 'Eshita Hasan',
       'Mehedi Chowdhury', 'Mehedi Hasan', 'Munira Khan', 'Firoz Biswas',
       'Wahida Islam', 'Maliha Uddin', 'Roksana Paul', 'Sinthia Rahman',
       'Nurul Sheikh', 'Taslima Sharma', 'Jahangir Dey', 'Nusrat Sharma',
       'Sakib Chowdhury', 'Parveen Barua', 'Sufia Khatun', 'Ismail Uddin',
       'Omar Dey', 'Ayesha Rahman', 'Liton Khan', 'Yasmeen Akhter',
       'Jahangir Talukder', 'Anisur Khan', 'Abir Faruq', 'Samira Sheikh',
       'Enamul Ahmed', 'Anisur Saha', 'Junaid Sharma', 'Minara Bhuiyan',
       'Shamima Akhter', 'Nazmul Ahmed', 'Yasmin Khan', 'Parvin Majumder',
       'Moriam Hawlader', 'Lutfun Nath', 'Iffat Faruq', 'Ayesha Islam',
       'Nusrat Islam', 'Tania Saha', 'Dulal Begum', 'Touhid Sarkar',
       'Wahiduzzaman Khan', 'Ismail Islam', 'Nurul Talukder',
       'Quazi Chowdhury', 'Amena Mridha', 'Dulal Paul', 'Golam Ferdous',
       'Hasan Bhuiyan', 'Munira Rahman', 'Kalinda Sarkar', 'Omar Bhuiyan',
       'Sufia Hawlader', 'Laila Talukder', 'Masud Biswas',
       'Kamrul Khatun', 'Tahmina Hossain', 'Ismail Sheikh',
       'Rubel Chowdhury', 'Bristy Sharma', 'Priya Barua', 'Khalid Ahmed',
       'Sharmin Rahman', 'Samira Khan', 'Zobair Hossain', 'Taslima Faruq',
       'Wahiduzzaman Majumder', 'Sadia Paul', 'Firoz Khan'], dtype=object)

In [33]:
df.CompletionStatus.unique()

array(['Completed', 'In Progress', 'Not Started'], dtype=object)

In [34]:
len(df.CompletionStatus.unique())

3

In [35]:
df['Data Structure Marks'].unique()

array([69.7, 65.9, 77.5, 89.7, 89. , 77.1, 96.5, 97.1,  nan, 66.6, 70.4,
       90.9, 73.2, 85.6, 72.6, 83.9, 81.1, 89.8, 96.4, 94.4, 75.1, 82.3,
       78.5, 69.5, 95.2, 70.1, 68.8, 95.6, 91.1, 74.5, 97.7, 89.1, 89.4,
       87.6, 84.7, 86.5, 73.5, 75.9, 72. , 76.4, 79.6, 97.3, 72.4, 91.3,
       76.6, 72.2, 90.8, 84.8, 89.5, 65.4, 86.4, 70.3, 72.9, 71.6, 83.5,
       73.6, 88.7, 93.6, 81.4, 89.6, 96. , 93. , 96.9, 92.1, 87.7, 78. ,
       71.5, 77.4, 94.7, 87.9])

In [36]:
len(df['Data Structure Marks'].unique())

70

In [37]:
df['Data Structure Marks'].nunique()

69

In [38]:
df.nunique()

StudentID               100
FullName                100
Data Structure Marks     69
Algorithm Marks          64
Python Marks             65
CompletionStatus          3
EnrollmentDate           87
Instructor                5
Location                  8
Country                   1
Total Marks              65
A+ in DS                  2
Passes in DS              2
First Name               70
dtype: int64

In [40]:
df.unique()

# It only works for series

AttributeError: 'DataFrame' object has no attribute 'unique'

In [42]:
df.isnull()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passes in DS,First Name
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False,False,False,False,False
97,False,False,True,True,True,False,False,False,False,False,True,False,False,False
98,False,False,False,False,False,False,False,False,False,False,False,False,False,False
99,False,False,True,True,True,False,False,False,False,False,True,False,False,False

In [43]:
df.isnull().sum()

StudentID                0
FullName                 0
Data Structure Marks    25
Algorithm Marks         25
Python Marks            28
CompletionStatus         0
EnrollmentDate           0
Instructor               0
Location                 0
Country                  0
Total Marks             33
A+ in DS                 0
Passes in DS             0
First Name               0
dtype: int64

In [44]:
df['Data Structure Marks'].isnull()

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97     True
98    False
99     True
Name: Data Structure Marks, Length: 100, dtype: bool

In [45]:
df['Data Structure Marks'].isnull().sum()

np.int64(25)

In [46]:
df['Data Structure Marks'].notnull()

0      True
1      True
2      True
3      True
4      True
      ...
95     True
96     True
97    False
98     True
99    False
Name: Data Structure Marks, Length: 100, dtype: bool

In [47]:
df['Data Structure Marks'].notnull().sum()

np.int64(75)

In [48]:
df['Data Structure Marks'].hasnans

True

In [49]:
df['FullName'].hasnans

False

In [53]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [54]:
df.duplicated().sum()

np.int64(0)

In [56]:
df.drop_duplicates(inplace = True)

In [57]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passes in DS,First Name
0,PH1001,Amena Islam,69.7,68.5,90.2,Completed,2024-01-24,Mr. Haque,Rangpur,Bangladesh,228.4,A,False,Amena
1,PH1002,Kamal Akhter,65.9,71.8,87.1,Completed,2024-02-07,Ms. Salma,Mymensingh,Bangladesh,224.8,A,False,Kamal
2,PH1003,Tania Bhuiyan,77.5,75.8,90.6,In Progress,2024-01-25,Mr. Karim,Chattogram,Bangladesh,243.9,A,True,Tania
3,PH1004,Sajid Hasan,89.7,84.5,NaN,In Progress,2024-06-28,Ms. Rina,Chattogram,Bangladesh,NaN,A,True,Sajid
4,PH1005,Quamrul Sarkar,89.0,66.6,72.7,Completed,2024-11-20,Mr. Karim,Rajshahi,Bangladesh,228.3,A,True,Quamrul
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,PH1096,Zobair Hossain,77.4,69.5,95.9,Completed,2025-05-26,Ms. Rina,Sylhet,Bangladesh,242.8,A,True,Zobair
96,PH1097,Taslima Faruq,94.7,95.5,96.1,In Progress,2024-09-12,Mr. David,Barishal,Bangladesh,286.3,A+,True,Taslima
97,PH1098,Wahiduzzaman Majumder,NaN,NaN,NaN,In Progress,2024-02-05,Mr. Haque,Barishal,Bangladesh,NaN,A,False,Wahiduzzaman
98,PH1099,Sadia Paul,87.9,87.9,84.9,Completed,2024-01-09,Mr. David,Chattogram,Bangladesh,260.7,A,True,Sadia
99,PH1100,Firoz Khan,NaN,NaN,NaN,Not Started,2024-08-01,Ms. Salma,Chattogram,Bangladesh,NaN,A,False,Firoz

In [60]:
df.drop_duplicates(subset = ['Algorithm Marks'], inplace = True)

In [61]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passes in DS,First Name
0,PH1001,Amena Islam,69.7,68.5,90.2,Completed,2024-01-24,Mr. Haque,Rangpur,Bangladesh,228.4,A,False,Amena
1,PH1002,Kamal Akhter,65.9,71.8,87.1,Completed,2024-02-07,Ms. Salma,Mymensingh,Bangladesh,224.8,A,False,Kamal
2,PH1003,Tania Bhuiyan,77.5,75.8,90.6,In Progress,2024-01-25,Mr. Karim,Chattogram,Bangladesh,243.9,A,True,Tania
3,PH1004,Sajid Hasan,89.7,84.5,NaN,In Progress,2024-06-28,Ms. Rina,Chattogram,Bangladesh,NaN,A,True,Sajid
4,PH1005,Quamrul Sarkar,89.0,66.6,72.7,Completed,2024-11-20,Mr. Karim,Rajshahi,Bangladesh,228.3,A,True,Quamrul
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,PH1093,Khalid Ahmed,78.0,77.2,75.1,Completed,2025-07-28,Mr. Karim,Rangpur,Bangladesh,230.3,A,True,Khalid
94,PH1095,Samira Khan,71.5,73.5,90.7,Completed,2024-10-26,Ms. Salma,Chattogram,Bangladesh,235.7,A,True,Samira
95,PH1096,Zobair Hossain,77.4,69.5,95.9,Completed,2025-05-26,Ms. Rina,Sylhet,Bangladesh,242.8,A,True,Zobair
96,PH1097,Taslima Faruq,94.7,95.5,96.1,In Progress,2024-09-12,Mr. David,Barishal,Bangladesh,286.3,A+,True,Taslima
98,PH1099,Sadia Paul,87.9,87.9,84.9,Completed,2024-01-09,Mr. David,Chattogram,Bangladesh,260.7,A,True,Sadia

In [62]:
df1

,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passes in DS,First Name
0,0,PH1001,Amena Islam,69.7,68.5,90.2,Completed,2024-01-24,Mr. Haque,Rangpur,Bangladesh,228.4,A,False,Amena
1,1,PH1002,Kamal Akhter,65.9,71.8,87.1,Completed,2024-02-07,Ms. Salma,Mymensingh,Bangladesh,224.8,A,False,Kamal
2,2,PH1003,Tania Bhuiyan,77.5,75.8,90.6,In Progress,2024-01-25,Mr. Karim,Chattogram,Bangladesh,243.9,A,True,Tania
3,3,PH1004,Sajid Hasan,89.7,84.5,NaN,In Progress,2024-06-28,Ms. Rina,Chattogram,Bangladesh,NaN,A,True,Sajid
4,4,PH1005,Quamrul Sarkar,89.0,66.6,72.7,Completed,2024-11-20,Mr. Karim,Rajshahi,Bangladesh,228.3,A,True,Quamrul
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,PH1096,Zobair Hossain,77.4,69.5,95.9,Completed,2025-05-26,Ms. Rina,Sylhet,Bangladesh,242.8,A,True,Zobair
96,96,PH1097,Taslima Faruq,94.7,95.5,96.1,In Progress,2024-09-12,Mr. David,Barishal,Bangladesh,286.3,A+,True,Taslima
97,97,PH1098,Wahiduzzaman Majumder,NaN,NaN,NaN,In Progress,2024-02-05,Mr. Haque,Barishal,Bangladesh,NaN,A,False,Wahiduzzaman
98,98,PH1099,Sadia Paul,87.9,87.9,84.9,Completed,2024-01-09,Mr. David,Chattogram,Bangladesh,260.7,A,True,Sadia
99,99,PH1100,Firoz Khan,NaN,NaN,NaN,Not Started,2024-08-01,Ms. Salma,Chattogram,Bangladesh,NaN,A,False,Firoz

In [63]:
df1.dropna()

,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passes in DS,First Name
0,0,PH1001,Amena Islam,69.7,68.5,90.2,Completed,2024-01-24,Mr. Haque,Rangpur,Bangladesh,228.4,A,False,Amena
1,1,PH1002,Kamal Akhter,65.9,71.8,87.1,Completed,2024-02-07,Ms. Salma,Mymensingh,Bangladesh,224.8,A,False,Kamal
2,2,PH1003,Tania Bhuiyan,77.5,75.8,90.6,In Progress,2024-01-25,Mr. Karim,Chattogram,Bangladesh,243.9,A,True,Tania
4,4,PH1005,Quamrul Sarkar,89.0,66.6,72.7,Completed,2024-11-20,Mr. Karim,Rajshahi,Bangladesh,228.3,A,True,Quamrul
5,5,PH1006,Tanvir Das,77.1,87.8,88.9,Completed,2024-05-15,Mr. Karim,Sylhet,Bangladesh,253.8,A,True,Tanvir
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,92,PH1093,Khalid Ahmed,78.0,77.2,75.1,Completed,2025-07-28,Mr. Karim,Rangpur,Bangladesh,230.3,A,True,Khalid
94,94,PH1095,Samira Khan,71.5,73.5,90.7,Completed,2024-10-26,Ms. Salma,Chattogram,Bangladesh,235.7,A,True,Samira
95,95,PH1096,Zobair Hossain,77.4,69.5,95.9,Completed,2025-05-26,Ms. Rina,Sylhet,Bangladesh,242.8,A,True,Zobair
96,96,PH1097,Taslima Faruq,94.7,95.5,96.1,In Progress,2024-09-12,Mr. David,Barishal,Bangladesh,286.3,A+,True,Taslima
98,98,PH1099,Sadia Paul,87.9,87.9,84.9,Completed,2024-01-09,Mr. David,Chattogram,Bangladesh,260.7,A,True,Sadia

In [66]:
df1.dropna(how = 'all', inplace = True)

In [68]:
df.dropna(subset = ['Python Marks'])

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passes in DS,First Name
0,PH1001,Amena Islam,69.7,68.5,90.2,Completed,2024-01-24,Mr. Haque,Rangpur,Bangladesh,228.4,A,False,Amena
1,PH1002,Kamal Akhter,65.9,71.8,87.1,Completed,2024-02-07,Ms. Salma,Mymensingh,Bangladesh,224.8,A,False,Kamal
2,PH1003,Tania Bhuiyan,77.5,75.8,90.6,In Progress,2024-01-25,Mr. Karim,Chattogram,Bangladesh,243.9,A,True,Tania
4,PH1005,Quamrul Sarkar,89.0,66.6,72.7,Completed,2024-11-20,Mr. Karim,Rajshahi,Bangladesh,228.3,A,True,Quamrul
5,PH1006,Tanvir Das,77.1,87.8,88.9,Completed,2024-05-15,Mr. Karim,Sylhet,Bangladesh,253.8,A,True,Tanvir
6,PH1007,Osman Mimi,96.5,88.4,72.5,Completed,2025-03-15,Mr. Karim,Rajshahi,Bangladesh,257.4,A+,True,Osman
7,PH1008,Kamal Talukder,97.1,94.8,75.7,Completed,2024-07-09,Ms. Rina,Mymensingh,Bangladesh,267.6,A+,True,Kamal
9,PH1010,Rezaul Khan,66.6,68.7,86.3,Completed,2025-03-17,Ms. Rina,Chattogram,Bangladesh,221.6,A,False,Rezaul
11,PH1012,Gitika Bhuiyan,70.4,65.1,89.6,Completed,2024-11-11,Mr. Haque,Sylhet,Bangladesh,225.1,A,True,Gitika
12,PH1013,Masud Hasan,90.9,83.3,91.5,Completed,2024-11-10,Mr. Karim,Barishal,Bangladesh,265.7,A+,True,Masud
13,PH1014,Liton Akhter,73.2,84.3,67.7,Completed,2024-02-12,Mr. Karim,Sylhet,Bangladesh,225.2,A,True,Liton
14,PH1015,Afsana Hawlader,85.6,97.8,96.6,Completed,2024-09-06,Ms. Salma,Khulna,Bangladesh,280.0,A,True,Afsana
15,PH1016,Sinthia Nath,72.6,76.5,85.0,Completed,2025-08-17,Ms. Salma,Dhaka,Bangladesh,234.1,A,True,Sinthia
17,PH1018,Tahmina Faruq,81.1,78.8,68.2,Completed,2025-12-19,Mr. David,Rangpur,Bangladesh,228.1,A,True,Tahmina
18,PH1019,Golam Majumder,89.8,92.2,68.7,Completed,2024-12-02,Mr. Haque,Mymensingh,Bangladesh,250.7,A,True,Golam
19,PH1020,Babul Saha,96.4,80.1,94.3,Completed,2025-03-09,Mr. Karim,Dhaka,Bangladesh,270.8,A+,True,Babul
21,PH1022,Jahangir Sarkar,75.1,97.9,84.7,Completed,2025-07-23,Mr. David,Dhaka,Bangladesh,257.7,A,True,Jahangir
22,PH1023,Mahmudul Hawlader,82.3,93.9,67.3,Completed,2024-09-28,Ms. Salma,Rangpur,Bangladesh,243.5,A,True,Mahmudul
25,PH1026,Jahangir Hasan,69.5,76.9,67.3,Completed,2024-02-18,Mr. David,Sylhet,Bangladesh,213.7,A,False,Jahangir
26,PH1027,Ismail Mondal,95.2,72.8,93.7,In Progress,2024-10-26,Mr. David,Chattogram,Bangladesh,261.7,A+,True,Ismail
29,PH1030,Nurul Barua,68.8,97.1,88.5,Completed,2025-09-23,Mr. Karim,Barishal,Bangladesh,254.4,A,False,Nurul
30,PH1031,Sumon Sharma,95.6,92.1,94.3,Completed,2024-07-05,Ms. Salma,Rajshahi,Bangladesh,282.0,A+,True,Sumon
32,PH1033,Mehedi Chowdhury,91.1,81.1,88.1,In Progress,2024-07-01,Ms. Salma,Khulna,Bangladesh,260.3,A+,True,Mehedi
34,PH1035,Munira Khan,74.5,67.4,91.3,Completed,2024-04-01,Mr. Haque,Rangpur,Bangladesh,233.2,A,True,Munira
35,PH1036,Firoz Biswas,97.7,74.0,68.7,Completed,2024-01-04,Mr. David,Rangpur,Bangladesh,240.4,A+,True,Firoz
38,PH1039,Roksana Paul,87.6,77.9,90.4,Completed,2024-12-10,Mr. Haque,Khulna,Bangladesh,255.9,A,True,Roksana
39,PH1040,Sinthia Rahman,84.7,87.3,80.8,Completed,2024-05-10,Ms. Salma,Mymensingh,Bangladesh,252.8,A,True,Sinthia
40,PH1041,Nurul Sheikh,86.5,76.4,92.8,Completed,2024-11-03,Mr. David,Rajshahi,Bangladesh,255.7,A,True,Nurul
44,PH1045,Sakib Chowdhury,73.5,93.8,80.5,Completed,2025-12-17,Mr. Haque,Barishal,Bangladesh,247.8,A,True,Sakib
47,PH1048,Ismail Uddin,75.9,83.4,69.7,Completed,2024-12-10,Ms. Salma,Rajshahi,Bangladesh,229.0,A,True,Ismail
48,PH1049,Omar Dey,72.0,79.3,95.8,Completed,2025-07-11,Mr. Karim,Rangpur,Bangladesh,247.1,A,True,Omar
50,PH1051,Liton Khan,76.4,88.1,78.7,Completed,2025-05-14,Ms. Rina,Sylhet,Bangladesh,243.2,A,True,Liton
51,PH1052,Yasmeen Akhter,79.6,94.5,71.2,Completed,2024-07-19,Mr. David,Rajshahi,Bangladesh,245.3,A,True,Yasmeen
54,PH1055,Abir Faruq,72.4,88.8,91.1,Completed,2024-08-22,Mr. Haque,Chattogram,Bangladesh,252.3,A,True,Abir
61,PH1062,Nazmul Ahmed,90.8,88.5,87.0,Completed,2025-02-08,Mr. Karim,Chattogram,Bangladesh,266.3,A+,True,Nazmul
63,PH1064,Parvin Majumder,89.5,75.7,90.3,Completed,2024-05-10,Ms. Salma,Rajshahi,Bangladesh,255.5,A,True,Parvin
66,PH1067,Iffat Faruq,65.4,74.7,81.3,Completed,2025-11-28,Mr. Karim,Khulna,Bangladesh,221.4,A,False,Iffat
67,PH1068,Ayesha Islam,86.4,66.8,70.1,Completed,2025-02-13,Mr. David,Chattogram,Bangladesh,223.3,A,True,Ayesha
70,PH1071,Dulal Begum,70.3,78.9,88.4,Completed,2024-03-08,Mr. Karim,Rajshahi,Bangladesh,237.6,A,True,Dulal
74,PH1075,Nurul Talukder,97.7,93.4,84.6,Completed,2024-10-09,Mr. David,Dhaka,Bangladesh,275.7,A+,True,Nurul
76,PH1077,Amena Mridha,75.9,68.6,70.5,Completed,2024-02-16,Ms. Rina,Khulna,Bangladesh,215.0,A,True,Amena
77,PH1078,Dulal Paul,73.6,68.9,91.3,Completed,2025-09-02,Mr. Karim,Mymensingh,Bangladesh,233.8,A,True,Dulal
79,PH1080,Hasan Bhuiyan,88.7,69.1,98.1,Completed,2024-09-05,Ms. Salma,Sylhet,Bangladesh,255.9,A,True,Hasan
82,PH1083,Omar Bhuiyan,89.6,92.6,85.7,In Progress,2024-07-11,Ms. Rina,Sylhet,Bangladesh,267.9,A,True,Omar
83,PH1084,Sufia Hawlader,75.9,71.4,88.7,Completed,2025-06-11,Ms. Salma,Rangpur,Bangladesh,236.0,A,True,Sufia
84,PH1085,Laila Talukder,87.6,92.9,98.3,Completed,2025-12-16,Mr. Karim,Sylhet,Bangladesh,278.8,A,True,Laila
85,PH1086,Masud Biswas,96.0,65.5,69.9,Completed,2025-02-28,Ms. Salma,Chattogram,Bangladesh,231.4,A+,True,Masud
86,PH1087,Kamrul Khatun,93.0,93.2,80.3,In Progress,2025-06-20,Mr. David,Mymensingh,Bangladesh,266.5,A+,True,Kamrul
87,PH1088,Tahmina Hossain,96.9,90.2,81.7,In Progress,2024-10-03,Mr. Karim,Chattogram,Bangladesh,268.8,A+,True,Tahmina
88,PH1089,Ismail Sheikh,92.1,75.0,77.7,Completed,2024-12-10,Mr. Haque,Rangpur,Bangladesh,244.8,A+,True,Ismail
90,PH1091,Bristy Sharma,87.7,95.6,80.8,Completed,2024-04-15,Mr. Haque,Sylhet,Bangladesh,264.1,A,True,Bristy
92,PH1093,Khalid Ahmed,78.0,77.2,75.1,Completed,2025-07-28,Mr. Karim,Rangpur,Bangladesh,230.3,A,True,Khalid
94,PH1095,Samira Khan,71.5,73.5,90.7,Completed,2024-10-26,Ms. Salma,Chattogram,Bangladesh,235.7,A,True,Samira
95,PH1096,Zobair Hossain,77.4,69.5,95.9,Completed,2025-05-26,Ms. Rina,Sylhet,Bangladesh,242.8,A,True,Zobair
96,PH1097,Taslima Faruq,94.7,95.5,96.1,In Progress,2024-09-12,Mr. David,Barishal,Bangladesh,286.3,A+,True,Taslima
98,PH1099,Sadia Paul,87.9,87.9,84.9,Completed,2024-01-09,Mr. David,Chattogram,Bangladesh,260.7,A,True,Sadia

In [69]:
df.dropna(subset = ['Python Marks','Algorithm Marks'])

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passes in DS,First Name
0,PH1001,Amena Islam,69.7,68.5,90.2,Completed,2024-01-24,Mr. Haque,Rangpur,Bangladesh,228.4,A,False,Amena
1,PH1002,Kamal Akhter,65.9,71.8,87.1,Completed,2024-02-07,Ms. Salma,Mymensingh,Bangladesh,224.8,A,False,Kamal
2,PH1003,Tania Bhuiyan,77.5,75.8,90.6,In Progress,2024-01-25,Mr. Karim,Chattogram,Bangladesh,243.9,A,True,Tania
4,PH1005,Quamrul Sarkar,89.0,66.6,72.7,Completed,2024-11-20,Mr. Karim,Rajshahi,Bangladesh,228.3,A,True,Quamrul
5,PH1006,Tanvir Das,77.1,87.8,88.9,Completed,2024-05-15,Mr. Karim,Sylhet,Bangladesh,253.8,A,True,Tanvir
6,PH1007,Osman Mimi,96.5,88.4,72.5,Completed,2025-03-15,Mr. Karim,Rajshahi,Bangladesh,257.4,A+,True,Osman
7,PH1008,Kamal Talukder,97.1,94.8,75.7,Completed,2024-07-09,Ms. Rina,Mymensingh,Bangladesh,267.6,A+,True,Kamal
9,PH1010,Rezaul Khan,66.6,68.7,86.3,Completed,2025-03-17,Ms. Rina,Chattogram,Bangladesh,221.6,A,False,Rezaul
11,PH1012,Gitika Bhuiyan,70.4,65.1,89.6,Completed,2024-11-11,Mr. Haque,Sylhet,Bangladesh,225.1,A,True,Gitika
12,PH1013,Masud Hasan,90.9,83.3,91.5,Completed,2024-11-10,Mr. Karim,Barishal,Bangladesh,265.7,A+,True,Masud
13,PH1014,Liton Akhter,73.2,84.3,67.7,Completed,2024-02-12,Mr. Karim,Sylhet,Bangladesh,225.2,A,True,Liton
14,PH1015,Afsana Hawlader,85.6,97.8,96.6,Completed,2024-09-06,Ms. Salma,Khulna,Bangladesh,280.0,A,True,Afsana
15,PH1016,Sinthia Nath,72.6,76.5,85.0,Completed,2025-08-17,Ms. Salma,Dhaka,Bangladesh,234.1,A,True,Sinthia
17,PH1018,Tahmina Faruq,81.1,78.8,68.2,Completed,2025-12-19,Mr. David,Rangpur,Bangladesh,228.1,A,True,Tahmina
18,PH1019,Golam Majumder,89.8,92.2,68.7,Completed,2024-12-02,Mr. Haque,Mymensingh,Bangladesh,250.7,A,True,Golam
19,PH1020,Babul Saha,96.4,80.1,94.3,Completed,2025-03-09,Mr. Karim,Dhaka,Bangladesh,270.8,A+,True,Babul
21,PH1022,Jahangir Sarkar,75.1,97.9,84.7,Completed,2025-07-23,Mr. David,Dhaka,Bangladesh,257.7,A,True,Jahangir
22,PH1023,Mahmudul Hawlader,82.3,93.9,67.3,Completed,2024-09-28,Ms. Salma,Rangpur,Bangladesh,243.5,A,True,Mahmudul
25,PH1026,Jahangir Hasan,69.5,76.9,67.3,Completed,2024-02-18,Mr. David,Sylhet,Bangladesh,213.7,A,False,Jahangir
26,PH1027,Ismail Mondal,95.2,72.8,93.7,In Progress,2024-10-26,Mr. David,Chattogram,Bangladesh,261.7,A+,True,Ismail
29,PH1030,Nurul Barua,68.8,97.1,88.5,Completed,2025-09-23,Mr. Karim,Barishal,Bangladesh,254.4,A,False,Nurul
30,PH1031,Sumon Sharma,95.6,92.1,94.3,Completed,2024-07-05,Ms. Salma,Rajshahi,Bangladesh,282.0,A+,True,Sumon
32,PH1033,Mehedi Chowdhury,91.1,81.1,88.1,In Progress,2024-07-01,Ms. Salma,Khulna,Bangladesh,260.3,A+,True,Mehedi
34,PH1035,Munira Khan,74.5,67.4,91.3,Completed,2024-04-01,Mr. Haque,Rangpur,Bangladesh,233.2,A,True,Munira
35,PH1036,Firoz Biswas,97.7,74.0,68.7,Completed,2024-01-04,Mr. David,Rangpur,Bangladesh,240.4,A+,True,Firoz
38,PH1039,Roksana Paul,87.6,77.9,90.4,Completed,2024-12-10,Mr. Haque,Khulna,Bangladesh,255.9,A,True,Roksana
39,PH1040,Sinthia Rahman,84.7,87.3,80.8,Completed,2024-05-10,Ms. Salma,Mymensingh,Bangladesh,252.8,A,True,Sinthia
40,PH1041,Nurul Sheikh,86.5,76.4,92.8,Completed,2024-11-03,Mr. David,Rajshahi,Bangladesh,255.7,A,True,Nurul
44,PH1045,Sakib Chowdhury,73.5,93.8,80.5,Completed,2025-12-17,Mr. Haque,Barishal,Bangladesh,247.8,A,True,Sakib
47,PH1048,Ismail Uddin,75.9,83.4,69.7,Completed,2024-12-10,Ms. Salma,Rajshahi,Bangladesh,229.0,A,True,Ismail
48,PH1049,Omar Dey,72.0,79.3,95.8,Completed,2025-07-11,Mr. Karim,Rangpur,Bangladesh,247.1,A,True,Omar
50,PH1051,Liton Khan,76.4,88.1,78.7,Completed,2025-05-14,Ms. Rina,Sylhet,Bangladesh,243.2,A,True,Liton
51,PH1052,Yasmeen Akhter,79.6,94.5,71.2,Completed,2024-07-19,Mr. David,Rajshahi,Bangladesh,245.3,A,True,Yasmeen
54,PH1055,Abir Faruq,72.4,88.8,91.1,Completed,2024-08-22,Mr. Haque,Chattogram,Bangladesh,252.3,A,True,Abir
61,PH1062,Nazmul Ahmed,90.8,88.5,87.0,Completed,2025-02-08,Mr. Karim,Chattogram,Bangladesh,266.3,A+,True,Nazmul
63,PH1064,Parvin Majumder,89.5,75.7,90.3,Completed,2024-05-10,Ms. Salma,Rajshahi,Bangladesh,255.5,A,True,Parvin
66,PH1067,Iffat Faruq,65.4,74.7,81.3,Completed,2025-11-28,Mr. Karim,Khulna,Bangladesh,221.4,A,False,Iffat
67,PH1068,Ayesha Islam,86.4,66.8,70.1,Completed,2025-02-13,Mr. David,Chattogram,Bangladesh,223.3,A,True,Ayesha
70,PH1071,Dulal Begum,70.3,78.9,88.4,Completed,2024-03-08,Mr. Karim,Rajshahi,Bangladesh,237.6,A,True,Dulal
74,PH1075,Nurul Talukder,97.7,93.4,84.6,Completed,2024-10-09,Mr. David,Dhaka,Bangladesh,275.7,A+,True,Nurul
76,PH1077,Amena Mridha,75.9,68.6,70.5,Completed,2024-02-16,Ms. Rina,Khulna,Bangladesh,215.0,A,True,Amena
77,PH1078,Dulal Paul,73.6,68.9,91.3,Completed,2025-09-02,Mr. Karim,Mymensingh,Bangladesh,233.8,A,True,Dulal
79,PH1080,Hasan Bhuiyan,88.7,69.1,98.1,Completed,2024-09-05,Ms. Salma,Sylhet,Bangladesh,255.9,A,True,Hasan
82,PH1083,Omar Bhuiyan,89.6,92.6,85.7,In Progress,2024-07-11,Ms. Rina,Sylhet,Bangladesh,267.9,A,True,Omar
83,PH1084,Sufia Hawlader,75.9,71.4,88.7,Completed,2025-06-11,Ms. Salma,Rangpur,Bangladesh,236.0,A,True,Sufia
84,PH1085,Laila Talukder,87.6,92.9,98.3,Completed,2025-12-16,Mr. Karim,Sylhet,Bangladesh,278.8,A,True,Laila
85,PH1086,Masud Biswas,96.0,65.5,69.9,Completed,2025-02-28,Ms. Salma,Chattogram,Bangladesh,231.4,A+,True,Masud
86,PH1087,Kamrul Khatun,93.0,93.2,80.3,In Progress,2025-06-20,Mr. David,Mymensingh,Bangladesh,266.5,A+,True,Kamrul
87,PH1088,Tahmina Hossain,96.9,90.2,81.7,In Progress,2024-10-03,Mr. Karim,Chattogram,Bangladesh,268.8,A+,True,Tahmina
88,PH1089,Ismail Sheikh,92.1,75.0,77.7,Completed,2024-12-10,Mr. Haque,Rangpur,Bangladesh,244.8,A+,True,Ismail
90,PH1091,Bristy Sharma,87.7,95.6,80.8,Completed,2024-04-15,Mr. Haque,Sylhet,Bangladesh,264.1,A,True,Bristy
92,PH1093,Khalid Ahmed,78.0,77.2,75.1,Completed,2025-07-28,Mr. Karim,Rangpur,Bangladesh,230.3,A,True,Khalid
94,PH1095,Samira Khan,71.5,73.5,90.7,Completed,2024-10-26,Ms. Salma,Chattogram,Bangladesh,235.7,A,True,Samira
95,PH1096,Zobair Hossain,77.4,69.5,95.9,Completed,2025-05-26,Ms. Rina,Sylhet,Bangladesh,242.8,A,True,Zobair
96,PH1097,Taslima Faruq,94.7,95.5,96.1,In Progress,2024-09-12,Mr. David,Barishal,Bangladesh,286.3,A+,True,Taslima
98,PH1099,Sadia Paul,87.9,87.9,84.9,Completed,2024-01-09,Mr. David,Chattogram,Bangladesh,260.7,A,True,Sadia

In [71]:
df1.fillna(0)

,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,A+ in DS,Passes in DS,First Name
0,0,PH1001,Amena Islam,69.7,68.5,90.2,Completed,2024-01-24,Mr. Haque,Rangpur,Bangladesh,228.4,A,False,Amena
1,1,PH1002,Kamal Akhter,65.9,71.8,87.1,Completed,2024-02-07,Ms. Salma,Mymensingh,Bangladesh,224.8,A,False,Kamal
2,2,PH1003,Tania Bhuiyan,77.5,75.8,90.6,In Progress,2024-01-25,Mr. Karim,Chattogram,Bangladesh,243.9,A,True,Tania
3,3,PH1004,Sajid Hasan,89.7,84.5,0.0,In Progress,2024-06-28,Ms. Rina,Chattogram,Bangladesh,0.0,A,True,Sajid
4,4,PH1005,Quamrul Sarkar,89.0,66.6,72.7,Completed,2024-11-20,Mr. Karim,Rajshahi,Bangladesh,228.3,A,True,Quamrul
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,PH1096,Zobair Hossain,77.4,69.5,95.9,Completed,2025-05-26,Ms. Rina,Sylhet,Bangladesh,242.8,A,True,Zobair
96,96,PH1097,Taslima Faruq,94.7,95.5,96.1,In Progress,2024-09-12,Mr. David,Barishal,Bangladesh,286.3,A+,True,Taslima
97,97,PH1098,Wahiduzzaman Majumder,0.0,0.0,0.0,In Progress,2024-02-05,Mr. Haque,Barishal,Bangladesh,0.0,A,False,Wahiduzzaman
98,98,PH1099,Sadia Paul,87.9,87.9,84.9,Completed,2024-01-09,Mr. David,Chattogram,Bangladesh,260.7,A,True,Sadia
99,99,PH1100,Firoz Khan,0.0,0.0,0.0,Not Started,2024-08-01,Ms. Salma,Chattogram,Bangladesh,0.0,A,False,Firoz