.loc[] হলো label-based indexing — row/column name দিয়ে select করে। .iloc[] হলো position-based — integer position দিয়ে select করে (0-based)। এই পার্থক্য না বুঝলে ML pipeline-এ ভুল data নিয়ে কাজ হবে।

| Concept               | Description                                                                                                                                                                  |
| --------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **`.loc[]`**          | Label-based indexing। Row/column **name** ব্যবহার করে select করে। Slice-এর ক্ষেত্রে **inclusive**।                                                                           |
| **`.iloc[]`**         | Position-based indexing। Row/column **integer position (0-based)** ব্যবহার করে select করে। Slice-এর ক্ষেত্রে **exclusive end**।                                              |
| **`df['col']`**       | Single column selection। Returns a Series।                                                                                                                                   |
| **`df[['c1','c2']]`** | Multiple column selection। Returns a DataFrame।                                                                                                                              |
| **`.at[]`**           | Single value access **label-based**, fast।                                                                                                                                   |
| **`.iat[]`**          | Single value access **position-based**, fast।                                                                                                                                |
| **ML Application**    | - Features: `X = df.loc[:, feature_cols]`<br>- Labels: `y = df['target']`<br>- Train/test split: `df.iloc[train_idx]`<br>- Update single value: `df.at[row_label, col_name]` |

In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('house_price_bd.csv')

df = pd.DataFrame(df)
df.head()

,Title,Bedrooms,Bathrooms,Floor_no,Occupancy_status,Floor_area,City,Price_in_taka,Location
0,We Are Offering You A Very Spacious 1960 Sq Ft...,3.0,4.0,3,vacant,1960.0,dhaka,"৳39,000,000","Gulshan 1, Gulshan"
1,Valuable 1705 Square Feet Apartment Is Ready T...,3.0,3.0,1,vacant,1705.0,dhaka,"৳16,900,000","Lake Circus Road, Kalabagan"
2,1370 square feet apartment is ready to sale in...,3.0,3.0,6,vacant,1370.0,dhaka,"৳12,500,000","Shukrabad, Dhanmondi"
3,2125 Square Feet Apartment For Sale In Bashund...,3.0,3.0,4,vacant,2125.0,dhaka,"৳20,000,000","Block L, Bashundhara R-A"
4,Buy This 2687 Square Feet Flat In The Nice Are...,3.0,3.0,4,vacant,2687.0,dhaka,"৳47,500,000","Road No 25, Banani"

In [10]:
df = df.drop(columns=['Title'])

In [11]:
df.head()

,Bedrooms,Bathrooms,Floor_no,Occupancy_status,Floor_area,City,Price_in_taka,Location
0,3.0,4.0,3,vacant,1960.0,dhaka,"৳39,000,000","Gulshan 1, Gulshan"
1,3.0,3.0,1,vacant,1705.0,dhaka,"৳16,900,000","Lake Circus Road, Kalabagan"
2,3.0,3.0,6,vacant,1370.0,dhaka,"৳12,500,000","Shukrabad, Dhanmondi"
3,3.0,3.0,4,vacant,2125.0,dhaka,"৳20,000,000","Block L, Bashundhara R-A"
4,3.0,3.0,4,vacant,2687.0,dhaka,"৳47,500,000","Road No 25, Banani"

In [12]:
df['Bedrooms']

0       3.0
1       3.0
2       3.0
3       3.0
4       3.0
       ...
3860    3.0
3861    2.0
3862    3.0
3863    3.0
3864    3.0
Name: Bedrooms, Length: 3865, dtype: float64

In [13]:
df[['Bedrooms','Bathrooms']]

      Bedrooms  Bathrooms
0          3.0        4.0
1          3.0        3.0
2          3.0        3.0
3          3.0        3.0
4          3.0        3.0
...        ...        ...
3860       3.0        3.0
3861       2.0        2.0
3862       3.0        3.0
3863       3.0        3.0
3864       3.0        3.0

[3865 rows x 2 columns]

In [14]:
df.head(3)

,Bedrooms,Bathrooms,Floor_no,Occupancy_status,Floor_area,City,Price_in_taka,Location
0,3.0,4.0,3,vacant,1960.0,dhaka,"৳39,000,000","Gulshan 1, Gulshan"
1,3.0,3.0,1,vacant,1705.0,dhaka,"৳16,900,000","Lake Circus Road, Kalabagan"
2,3.0,3.0,6,vacant,1370.0,dhaka,"৳12,500,000","Shukrabad, Dhanmondi"

In [17]:
df.loc[0:1,'Bedrooms':'Bathrooms']

   Bedrooms  Bathrooms
0       3.0        4.0
1       3.0        3.0

In [18]:
df.iloc[0:2,0:3]

   Bedrooms  Bathrooms Floor_no
0       3.0        4.0        3
1       3.0        3.0        1

| Feature                | `loc`                                                            | `iloc`                                             |
| ---------------------- | ---------------------------------------------------------------- | -------------------------------------------------- |
| Indexing basis         | **Row/column labels** (name-based)                               | **Integer positions** (position-based)             |
| Row slice              | Includes **last label**                                          | Excludes **last index** (Python-style)             |
| Column slice           | Includes **last label**                                          | Excludes **last index**                            |
| Can use boolean arrays | ✅                                                                | ✅                                                  |
| Examples               | `df.loc[0:2, 'A':'C']` → rows with label 0,1,2 and columns A,B,C | `df.iloc[0:3, 0:3]` → rows 0,1,2 and columns 0,1,2 |

In [20]:
df.loc[0:2,'Bedrooms':'Floor_no']

   Bedrooms  Bathrooms Floor_no
0       3.0        4.0        3
1       3.0        3.0        1
2       3.0        3.0        6

In [21]:
df.head()

,Bedrooms,Bathrooms,Floor_no,Occupancy_status,Floor_area,City,Price_in_taka,Location
0,3.0,4.0,3,vacant,1960.0,dhaka,"৳39,000,000","Gulshan 1, Gulshan"
1,3.0,3.0,1,vacant,1705.0,dhaka,"৳16,900,000","Lake Circus Road, Kalabagan"
2,3.0,3.0,6,vacant,1370.0,dhaka,"৳12,500,000","Shukrabad, Dhanmondi"
3,3.0,3.0,4,vacant,2125.0,dhaka,"৳20,000,000","Block L, Bashundhara R-A"
4,3.0,3.0,4,vacant,2687.0,dhaka,"৳47,500,000","Road No 25, Banani"

In [22]:
df.at[2,'Floor_no']

'6'

In [24]:
df[['Bedrooms','Floor_no']]

      Bedrooms Floor_no
0          3.0        3
1          3.0        1
2          3.0        6
3          3.0        4
4          3.0        4
...        ...      ...
3860       3.0        8
3861       2.0        7
3862       3.0        9
3863       3.0        9
3864       3.0        8

[3865 rows x 2 columns]

In [23]:
df.iat[2,2]

'6'