Real-world ML project-এ data সবসময় বাইরের file বা database থেকে আসে। Pandas বিভিন্ন format সমর্থন করে — CSV, Excel, JSON, SQL, Parquet ইত্যাদি। read_csv() সবচেয়ে বেশি ব্যবহৃত কারণ Kaggle সহ বেশিরভাগ dataset CSV format-এ থাকে।

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("F:/1. Skill/ML + DL/Dataset/Health Dataset.csv")

In [3]:
df

,temperature,heart_rate,pulse,bp_sys,bp_dia,humidity,fever,cough,chest_pain,shortness_of_breath,fatigue,headache,disease
0,36.6,106.2,101.6,152.9,87.0,47.9,0,0,1,1,1,0,Heart_Risk
1,39.5,102.0,99.8,103.9,79.5,47.6,1,1,0,0,1,0,Fever_Respiratory
2,36.5,79.4,78.7,91.2,64.9,39.9,0,0,0,0,0,0,Normal
3,36.7,85.8,90.7,148.1,79.8,46.4,0,0,1,1,1,0,Heart_Risk
4,38.2,92.3,95.9,114.9,62.5,34.4,1,1,0,0,1,0,Fever_Respiratory
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,36.7,85.9,84.9,119.6,77.5,35.9,0,0,0,0,0,0,Normal
99996,36.5,71.6,72.2,132.7,91.5,40.9,0,0,0,0,1,0,Hypertension
99997,36.6,117.7,120.6,156.6,89.0,34.8,0,0,1,1,1,0,Heart_Risk
99998,36.8,61.6,60.6,104.1,63.0,49.7,0,0,0,0,0,0,Normal
99999,36.3,75.5,73.9,106.0,78.0,44.8,0,0,0,0,0,0,Normal

In [10]:
df = pd.read_csv(
  'F:/1. Skill/ML + DL/Dataset/Health Dataset.csv',
  sep = ',',
  header = 0,
 
  # usecols = ['temperature','pulse'],
  nrows = 500,
  skiprows = 2,
  na_values = ['N/A','?','']
)

df

,39.5,102.0,99.8,103.9,79.5,47.6,1,1.1,0,0.1,1.2,0.2,Fever_Respiratory
0,36.5,79.4,78.7,91.2,64.9,39.9,0,0,0,0,0,0,Normal
1,36.7,85.8,90.7,148.1,79.8,46.4,0,0,1,1,1,0,Heart_Risk
2,38.2,92.3,95.9,114.9,62.5,34.4,1,1,0,0,1,0,Fever_Respiratory
3,36.8,111.8,106.9,119.1,92.6,42.1,0,0,1,1,1,0,Heart_Risk
4,38.5,114.3,111.0,104.1,71.5,48.3,1,1,1,1,1,1,Fever_Respiratory
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,39.0,102.4,97.9,107.6,80.7,37.7,1,1,0,0,1,0,Fever_Respiratory
496,36.8,75.6,73.5,145.3,90.7,48.8,0,0,0,1,0,0,Hypertension
497,36.5,91.7,90.9,101.3,66.9,36.6,0,0,0,0,0,0,Normal
498,36.6,83.5,81.6,135.4,83.7,48.8,0,0,1,0,0,0,Hypertension
499,36.8,73.5,72.1,93.7,70.2,41.7,0,0,0,0,0,0,Normal

If there excels then read like this,

In [12]:
#df_excel = pd.read_excel('data.xlsx', sheet_name='Sheet1')

In [13]:
# If there json then,
# df_json = pd.read_json('data.json')

In [15]:
df.head(5)

,39.5,102.0,99.8,103.9,79.5,47.6,1,1.1,0,0.1,1.2,0.2,Fever_Respiratory
0,36.5,79.4,78.7,91.2,64.9,39.9,0,0,0,0,0,0,Normal
1,36.7,85.8,90.7,148.1,79.8,46.4,0,0,1,1,1,0,Heart_Risk
2,38.2,92.3,95.9,114.9,62.5,34.4,1,1,0,0,1,0,Fever_Respiratory
3,36.8,111.8,106.9,119.1,92.6,42.1,0,0,1,1,1,0,Heart_Risk
4,38.5,114.3,111.0,104.1,71.5,48.3,1,1,1,1,1,1,Fever_Respiratory

In [16]:
df.head()

,39.5,102.0,99.8,103.9,79.5,47.6,1,1.1,0,0.1,1.2,0.2,Fever_Respiratory
0,36.5,79.4,78.7,91.2,64.9,39.9,0,0,0,0,0,0,Normal
1,36.7,85.8,90.7,148.1,79.8,46.4,0,0,1,1,1,0,Heart_Risk
2,38.2,92.3,95.9,114.9,62.5,34.4,1,1,0,0,1,0,Fever_Respiratory
3,36.8,111.8,106.9,119.1,92.6,42.1,0,0,1,1,1,0,Heart_Risk
4,38.5,114.3,111.0,104.1,71.5,48.3,1,1,1,1,1,1,Fever_Respiratory

In [17]:
df.head(2)

,39.5,102.0,99.8,103.9,79.5,47.6,1,1.1,0,0.1,1.2,0.2,Fever_Respiratory
0,36.5,79.4,78.7,91.2,64.9,39.9,0,0,0,0,0,0,Normal
1,36.7,85.8,90.7,148.1,79.8,46.4,0,0,1,1,1,0,Heart_Risk

In [19]:
df.shape

(500, 13)

In [20]:
df.memory_usage(deep=True).sum()

np.int64(78225)

Kaggle dataset, UCI Repository, custom CSV সব pd.read_csv() দিয়ে load হয়। nrows দিয়ে large file-এ quick prototype করা যায়। usecols দিয়ে শুধু প্রয়োজনীয় feature load করে memory save করা যায়।