In [5]:
import pandas as pd


wide = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 90, 78],
    'Science': [92, 88, 95],
    'English': [78, 82, 90]
})
wide = pd.DataFrame(wide)

wide

      Name  Math  Science  English
0    Alice    85       92       78
1      Bob    90       88       82
2  Charlie    78       95       90

In [4]:

long = wide.melt(
    id_vars=['Name'],
    value_vars=['Math', 'Science', 'English'],
    var_name='Subject',
    value_name='Score'
)

long

      Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     90
2  Charlie     Math     78
3    Alice  Science     92
4      Bob  Science     88
5  Charlie  Science     95
6    Alice  English     78
7      Bob  English     82
8  Charlie  English     90

In [6]:
back_wide = long.pivot(
    index   = 'Name',    # কোনটা row label হবে
    columns = 'Subject', # কোনটা column হবে
    values  = 'Score'    # cell-এ কী বসবে
)

In [7]:
back_wide

Subject  English  Math  Science
Name
Alice         78    85       92
Bob           82    90       88
Charlie       90    78       95

প্রতিটি concept বাংলায় বুঝি।

---

## Wide vs Long — মূল পার্থক্য

Wide format-এ প্রতিটি subject আলাদা column। Human পড়তে পারে সহজে, কিন্তু নতুন subject যোগ হলে column বাড়াতে হয়।

Long format-এ প্রতিটি observation আলাদা row। Column সংখ্যা কম কিন্তু row বেশি। Visualization library এবং groupby এই format পছন্দ করে।

---

## ① melt() — Wide থেকে Long

`id_vars` মানে যেটা পরিচয় দেয় সেটা — Name। `value_vars` মানে যেগুলো "গলিয়ে" row বানাবো — Math, Science, English। প্রতিটি Name × Subject combination একটা নতুন row হয়। Alice-এর ৩টা column ছিল, এখন Alice-এর ৩টা row।

---

## ② pivot() — Long থেকে Wide

`melt()`-এর উল্টো। `index` বলো কে row হবে, `columns` বলো কে column হবে, `values` বলো cell-এ কী বসবে।

`pivot()` আর `pivot_table()` এর পার্থক্য একটাই — একই index+column combination-এ duplicate থাকলে `pivot()` error দেবে, `pivot_table()` aggregate করে নেবে।

---

## ③ stack() / unstack() — কখন লাগে?

সাধারণ কাজে `melt/pivot` যথেষ্ট। `stack/unstack` লাগে যখন multi-level index থাকে — যেমন `groupby` বা `pivot_table` করার পরে যে complicated index তৈরি হয়, সেটা flatten করতে।

---

## সহজ নিয়ম

| কাজ | method |
|---|---|
| Wide → Long | `melt()` |
| Long → Wide | `pivot()` |
| Duplicate থাকলে Wide → | `pivot_table()` |
| sklearn-এ দেবো | Wide format |
| seaborn-এ দেবো | Long format |