| Concept                    | Description                                                                                                           |
| -------------------------- | --------------------------------------------------------------------------------------------------------------------- |
| **Slicing**                | DataFrame-এর নির্দিষ্ট অংশ select করা। Row, column, বা উভয়ই slice করা যায়। Efficient slicing memory ও time বাঁচায়। |
| **Row slice**              | `df[start:end]` → rows `start` থেকে `end-1` select করে।                                                               |
| **Column & row slice**     | `df.loc[row_labels, col_labels]` → label-based selection।<br>`df.iloc[row_pos, col_pos]` → position-based selection।  |
| **SQL-like filter**        | `df.query("condition")` → condition অনুযায়ী rows filter করে।                                                         |
| **Head & Tail**            | `df.head(n)` → first n rows।<br>`df.tail(n)` → last n rows।                                                           |
| **Random sample**          | `df.sample(n, random_state=seed)` → random n rows select করে reproducibly।                                            |
| **Feature & target split** | `X = df.iloc[:, :-1]` → সব rows, last column বাদ।<br>`y = df.iloc[:, -1]` → last column only।                         |

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('house_price_bd.csv')

In [3]:
df.head()

,Title,Bedrooms,Bathrooms,Floor_no,Occupancy_status,Floor_area,City,Price_in_taka,Location
0,We Are Offering You A Very Spacious 1960 Sq Ft...,3.0,4.0,3,vacant,1960.0,dhaka,"৳39,000,000","Gulshan 1, Gulshan"
1,Valuable 1705 Square Feet Apartment Is Ready T...,3.0,3.0,1,vacant,1705.0,dhaka,"৳16,900,000","Lake Circus Road, Kalabagan"
2,1370 square feet apartment is ready to sale in...,3.0,3.0,6,vacant,1370.0,dhaka,"৳12,500,000","Shukrabad, Dhanmondi"
3,2125 Square Feet Apartment For Sale In Bashund...,3.0,3.0,4,vacant,2125.0,dhaka,"৳20,000,000","Block L, Bashundhara R-A"
4,Buy This 2687 Square Feet Flat In The Nice Are...,3.0,3.0,4,vacant,2687.0,dhaka,"৳47,500,000","Road No 25, Banani"

In [4]:
df = df.drop(columns='Title')

In [5]:
df.head()

,Bedrooms,Bathrooms,Floor_no,Occupancy_status,Floor_area,City,Price_in_taka,Location
0,3.0,4.0,3,vacant,1960.0,dhaka,"৳39,000,000","Gulshan 1, Gulshan"
1,3.0,3.0,1,vacant,1705.0,dhaka,"৳16,900,000","Lake Circus Road, Kalabagan"
2,3.0,3.0,6,vacant,1370.0,dhaka,"৳12,500,000","Shukrabad, Dhanmondi"
3,3.0,3.0,4,vacant,2125.0,dhaka,"৳20,000,000","Block L, Bashundhara R-A"
4,3.0,3.0,4,vacant,2687.0,dhaka,"৳47,500,000","Road No 25, Banani"

In [6]:
df[2:5]

,Bedrooms,Bathrooms,Floor_no,Occupancy_status,Floor_area,City,Price_in_taka,Location
2,3.0,3.0,6,vacant,1370.0,dhaka,"৳12,500,000","Shukrabad, Dhanmondi"
3,3.0,3.0,4,vacant,2125.0,dhaka,"৳20,000,000","Block L, Bashundhara R-A"
4,3.0,3.0,4,vacant,2687.0,dhaka,"৳47,500,000","Road No 25, Banani"

In [7]:
df.head(3)

,Bedrooms,Bathrooms,Floor_no,Occupancy_status,Floor_area,City,Price_in_taka,Location
0,3.0,4.0,3,vacant,1960.0,dhaka,"৳39,000,000","Gulshan 1, Gulshan"
1,3.0,3.0,1,vacant,1705.0,dhaka,"৳16,900,000","Lake Circus Road, Kalabagan"
2,3.0,3.0,6,vacant,1370.0,dhaka,"৳12,500,000","Shukrabad, Dhanmondi"

In [8]:
df.tail(2)

,Bedrooms,Bathrooms,Floor_no,Occupancy_status,Floor_area,City,Price_in_taka,Location
3863,3.0,3.0,9,vacant,1300.0,gazipur,"৳5,200,000","Joydebpur, Gazipur Sadar Upazila"
3864,3.0,3.0,8,vacant,1350.0,gazipur,"৳4,500,000","Joydebpur, Gazipur Sadar Upazila"

In [9]:
df.sample(3,random_state=42)

,Bedrooms,Bathrooms,Floor_no,Occupancy_status,Floor_area,City,Price_in_taka,Location
2323,2.0,2.0,4,vacant,1003.0,chattogram,"৳5,000,000","Kobi Kazi Nazrul Islam Road, 33 No. Firingee B..."
1419,3.0,3.0,6,vacant,1200.0,dhaka,"৳5,500,000","Ahmed Nagar, Mirpur"
2477,NaN,NaN,NaN,NaN,NaN,chattogram,"৳4,500,000","Ali Nagar, Bayazid"

In [10]:
df['Price_in_taka']

0       ৳39,000,000
1       ৳16,900,000
2       ৳12,500,000
3       ৳20,000,000
4       ৳47,500,000
           ...
3860     ৳4,500,000
3861     ৳4,300,000
3862     ৳4,960,000
3863     ৳5,200,000
3864     ৳4,500,000
Name: Price_in_taka, Length: 3865, dtype: object

In [12]:
df.loc[0:2,'Bedrooms':'City']

   Bedrooms  Bathrooms Floor_no Occupancy_status  Floor_area   City
0       3.0        4.0        3           vacant      1960.0  dhaka
1       3.0        3.0        1           vacant      1705.0  dhaka
2       3.0        3.0        6           vacant      1370.0  dhaka

In [13]:
df.iloc[0:3,0:6]

   Bedrooms  Bathrooms Floor_no Occupancy_status  Floor_area   City
0       3.0        4.0        3           vacant      1960.0  dhaka
1       3.0        3.0        1           vacant      1705.0  dhaka
2       3.0        3.0        6           vacant      1370.0  dhaka

In [14]:
df.Price_in_taka

0       ৳39,000,000
1       ৳16,900,000
2       ৳12,500,000
3       ৳20,000,000
4       ৳47,500,000
           ...
3860     ৳4,500,000
3861     ৳4,300,000
3862     ৳4,960,000
3863     ৳5,200,000
3864     ৳4,500,000
Name: Price_in_taka, Length: 3865, dtype: object

In [16]:
df['Price_numeric'] = df['Price_in_taka'].replace({'৳':'',',':''},regex=True).astype(float)

In [17]:
df.head(3)

,Bedrooms,Bathrooms,Floor_no,Occupancy_status,Floor_area,City,Price_in_taka,Location,Price_numeric
0,3.0,4.0,3,vacant,1960.0,dhaka,"৳39,000,000","Gulshan 1, Gulshan",39000000.0
1,3.0,3.0,1,vacant,1705.0,dhaka,"৳16,900,000","Lake Circus Road, Kalabagan",16900000.0
2,3.0,3.0,6,vacant,1370.0,dhaka,"৳12,500,000","Shukrabad, Dhanmondi",12500000.0

In [19]:
subset = df.query('Floor_area > 2000 and Price_numeric > 20000000')
subset.head()

,Bedrooms,Bathrooms,Floor_no,Occupancy_status,Floor_area,City,Price_in_taka,Location,Price_numeric
4,3.0,3.0,4,vacant,2687.0,dhaka,"৳47,500,000","Road No 25, Banani",47500000.0
7,4.0,4.0,2,vacant,2318.0,dhaka,"৳23,000,000","Block D, Bashundhara R-A",23000000.0
17,3.0,3.0,4,vacant,2343.0,dhaka,"৳22,000,000","Sector 6, Uttara",22000000.0
21,4.0,4.0,2,vacant,3650.0,dhaka,"৳78,000,000","Gulshan 2, Gulshan",78000000.0
22,NaN,NaN,9,vacant,5000.0,dhaka,"৳110,000,000","Free School Street, Kathalbagan",110000000.0

In [22]:
df.head(2)

,Bedrooms,Bathrooms,Floor_no,Occupancy_status,Floor_area,City,Price_in_taka,Location,Price_numeric
0,3.0,4.0,3,vacant,1960.0,dhaka,"৳39,000,000","Gulshan 1, Gulshan",39000000.0
1,3.0,3.0,1,vacant,1705.0,dhaka,"৳16,900,000","Lake Circus Road, Kalabagan",16900000.0

In [ ]:
x = df.iloc[:,1:-2]
x

      Bathrooms Floor_no Occupancy_status  Floor_area     City Price_in_taka
0           4.0        3           vacant      1960.0    dhaka   ৳39,000,000
1           3.0        1           vacant      1705.0    dhaka   ৳16,900,000
2           3.0        6           vacant      1370.0    dhaka   ৳12,500,000
3           3.0        4           vacant      2125.0    dhaka   ৳20,000,000
4           3.0        4           vacant      2687.0    dhaka   ৳47,500,000
...         ...      ...              ...         ...      ...           ...
3860        3.0        8           vacant      1350.0  gazipur    ৳4,500,000
3861        2.0        7           vacant      1000.0  gazipur    ৳4,300,000
3862        3.0        9           vacant      1240.0  gazipur    ৳4,960,000
3863        3.0        9           vacant      1300.0  gazipur    ৳5,200,000
3864        3.0        8           vacant      1350.0  gazipur    ৳4,500,000

[3865 rows x 6 columns]

In [23]:
y = df.iloc[:, -2]

In [25]:
y = pd.DataFrame(y)
y

                              Location
0                   Gulshan 1, Gulshan
1          Lake Circus Road, Kalabagan
2                 Shukrabad, Dhanmondi
3             Block L, Bashundhara R-A
4                   Road No 25, Banani
...                                ...
3860  Joydebpur, Gazipur Sadar Upazila
3861   Chandana, Gazipur Sadar Upazila
3862  Joydebpur, Gazipur Sadar Upazila
3863  Joydebpur, Gazipur Sadar Upazila
3864  Joydebpur, Gazipur Sadar Upazila

[3865 rows x 1 columns]

In [26]:
df.at[2,'Floor_area']

np.float64(1370.0)

In [27]:
df.iat[2,4]

np.float64(1370.0)