Data preprocessing বা feature engineering-এর পরে processed data save করা দরকার। Pandas বিভিন্ন format-এ export করতে পারে। to_csv() সবচেয়ে portable, to_parquet() large dataset-এ fast ও compressed।

In [1]:
import pandas as pd

In [2]:
data = {'Name':['Alice','Bob'], 'Score':[95, 88]}

df = pd.DataFrame(data)

In [3]:
df

    Name  Score
0  Alice     95
1    Bob     88

In [8]:
df.to_csv('output.csv',index=False)

In [7]:
df.to_csv('output2.csv')

In [5]:
df.to_csv('output1.tsv',sep=' ',index=False)

In [9]:
df.to_excel('output.xlsx',sheet_name='Sheet1',index=False)

In [11]:
df.to_pickle('output.pkl')

In [12]:
df_back = pd.read_pickle('output.pkl')

In [13]:
df_back

    Name  Score
0  Alice     95
1    Bob     88

In [14]:
df.to_json('output.json',orient='records',lines=True,indent=2)