In [13]:
import pandas as pd

ml_results = {
  'Model':['KNN','Random Forest','Logistic Regression'],
  'Besk K':[5,100,None],
  'Accuracy':[22.22,33.55,66.66],
  'Train Time Sec':[0.1,0.3,4]
}

df = pd.DataFrame(ml_results)
df

                 Model  Besk K  Accuracy  Train Time Sec
0                  KNN     5.0     22.22             0.1
1        Random Forest   100.0     33.55             0.3
2  Logistic Regression     NaN     66.66             4.0

In [14]:
print(ml_results['Model'])

['KNN', 'Random Forest', 'Logistic Regression']

In [18]:
df[['Model']]

                 Model
0                  KNN
1        Random Forest
2  Logistic Regression

In [17]:
df[['Model','Accuracy']]

                 Model  Accuracy
0                  KNN     22.22
1        Random Forest     33.55
2  Logistic Regression     66.66

In [21]:
ml_results.keys()

dict_keys(['Model', 'Besk K', 'Accuracy', 'Train Time Sec'])

In [22]:
ml_results.values()

dict_values([['KNN', 'Random Forest', 'Logistic Regression'], [5, 100, None], [22.22, 33.55, 66.66], [0.1, 0.3, 4]])

In [23]:
ml_results

{'Model': ['KNN', 'Random Forest', 'Logistic Regression'],
 'Besk K': [5, 100, None],
 'Accuracy': [22.22, 33.55, 66.66],
 'Train Time Sec': [0.1, 0.3, 4]}