In [198]:
import numpy as np
import pandas as pd

np.random.seed(24)

num_employees = 50  # you can increase this if needed

# Employee data
emp_ids = np.arange(101, 101 + num_employees)
emp_ages = np.random.randint(20, 55, num_employees)
emp_income = np.random.randint(35000, 95000, num_employees)

# Fixed set of roles (repetition allowed)
roles_list = [
    "HR Manager",
    "Software Developer",
    "Accountant",
    "Marketing Executive",
    "Sales Executive",
    "Backend Developer",
    "HR Executive",
    "Financial Analyst",
    "Digital Marketer",
    "Operations Manager"
]

emp_roles = np.random.choice(roles_list, num_employees)

# Create DataFrame
data = pd.DataFrame({
    "emp_id": emp_ids,
    "emp_age": emp_ages,
    "emp_salary": emp_income,
    "role": emp_roles
})

# Save dataset
data.to_csv("staff_data.csv", index=False)

In [199]:
df = pd.read_csv("staff_data.csv")
df1 = df['emp_age'].to_numpy()
df2 = df['emp_salary'].to_numpy()

print(df1)
print("For Employee Age,")
print("Data Type: ", df1.dtype)
print("Number of Dimensions: ", df1.ndim)
print("Shape: ", df1.shape)
print("Number of size: ", df1.size)

print()
print(df2)
print("For Employee Salary,")
print("Data Type: ", df2.dtype)
print("Number of Dimensions: ", df2.ndim)
print("Shape: ", df2.shape)
print("Number of size: ", df2.size)

[54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
 53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
 31 50]
For Employee Age,
Data Type:  int64
Number of Dimensions:  1
Shape:  (50,)
Number of size:  50

[51725 38495 35452 82295 72187 58915 76159 92864 76155 90494 68641 48079
 56879 83682 94722 91041 48899 68744 63187 74146 75641 47678 76760 78354
 60584 79898 59682 71888 51086 73700 82550 71447 76100 72269 73314 87428
 94427 84188 52013 63326 44396 59500 55523 58602 90794 41061 82331 73048
 59727 50398]
For Employee Salary,
Data Type:  int64
Number of Dimensions:  1
Shape:  (50,)
Number of size:  50

In [200]:
df.head()

   emp_id  emp_age  emp_salary                role
0     101       54       51725          HR Manager
1     102       23       38495          Accountant
2     103       20       35452  Operations Manager
3     104       43       82295    Digital Marketer
4     105       37       72187   Backend Developer

In [201]:
maximum_sal = np.max(df2)
minimum_sal = np.min(df2)
average_sal = np.mean(df2)
average_age = np.mean(df1)
print("Maximum Salary: ", maximum_sal)
print("Minimum Salary: ", minimum_sal)
print("Average Salary: ", average_sal)
print("Average Age: ", average_age)

Maximum Salary:  94722
Minimum Salary:  35452
Average Salary:  68409.48
Average Age:  35.44

In [202]:
data = df.to_numpy()

new_array = data[(data[::,1] >= 25) & (data[::,1] <= 40) & (data[::,2] > 50000)]


print(new_array[::,1])
print(new_array[::,2])
print(new_array.shape[0])

[37 37 35 38 31 29 38 27 32 26 37 26 30 30 27 25 31]
[72187 58915 92864 90494 68641 56879 83682 94722 74146 78354 79898 59682
 73700 84188 52013 63326 59727]
17

In [203]:
chk = (df1 >= 25) & (df1 <= 40) & (df2 > 50000)

print(df1[chk])
print(df2[chk])
print(np.sum(chk))

[37 37 35 38 31 29 38 27 32 26 37 26 30 30 27 25 31]
[72187 58915 92864 90494 68641 56879 83682 94722 74146 78354 79898 59682
 73700 84188 52013 63326 59727]
17

In [204]:
new_arr =np.where(df1 >= (np.mean(df1)), (df1 + 2), (df1 + 4))


print("Original Array:" ,df1)
print("New Array:" , new_arr)
print("Mean: ", (np.mean(df1)))

Original Array: [54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
 53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
 31 50]
New Array: [56 27 24 45 39 39 25 39 28 40 35 39 33 40 31 47 53 50 24 36 53 55 25 30
 55 39 30 25 47 34 24 49 55 55 27 28 25 34 31 29 41 24 49 43 26 54 44 56
 35 52]
Mean:  35.44

In [205]:
role = data[::,3]
print(role)

con = (role == 'Software Developer') | (role == 'Backend Developer')


new_df2 = df2.copy()
new_df2[con] = new_df2[con] * 1.08

old_sal = np.sum(df2)
new_sal = np.sum(new_df2)


print()
print("Old Salary: ", old_sal)
print("New Salary: ", new_sal)
print("Differences: ", (new_sal - old_sal))

['HR Manager' 'Accountant' 'Operations Manager' 'Digital Marketer'
 'Backend Developer' 'HR Manager' 'Backend Developer' 'Sales Executive'
 'Sales Executive' 'HR Executive' 'Backend Developer'
 'Marketing Executive' 'Sales Executive' 'Operations Manager'
 'Digital Marketer' 'Financial Analyst' 'Sales Executive'
 'Operations Manager' 'Software Developer' 'Backend Developer'
 'Sales Executive' 'Sales Executive' 'Accountant' 'Software Developer'
 'HR Executive' 'Operations Manager' 'Digital Marketer' 'HR Executive'
 'Software Developer' 'Accountant' 'Sales Executive' 'Marketing Executive'
 'Digital Marketer' 'Backend Developer' 'Software Developer'
 'Software Developer' 'Sales Executive' 'Accountant' 'HR Manager'
 'Sales Executive' 'Marketing Executive' 'Digital Marketer' 'HR Executive'
 'Accountant' 'HR Executive' 'HR Manager' 'Software Developer'
 'Software Developer' 'Digital Marketer' 'Marketing Executive']

Old Salary:  3420474
New Salary:  3490239
Differences:  69765

In [206]:
df = pd.read_csv('staff_data.csv')

df.head(3)

   emp_id  emp_age  emp_salary                role
0     101       54       51725          HR Manager
1     102       23       38495          Accountant
2     103       20       35452  Operations Manager

In [207]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      50 non-null     int64
 1   emp_age     50 non-null     int64
 2   emp_salary  50 non-null     int64
 3   role        50 non-null     object
dtypes: int64(3), object(1)
memory usage: 1.7+ KB

In [208]:
df.describe()

          emp_id    emp_age    emp_salary
count   50.00000  50.000000     50.000000
mean   125.50000  35.440000  68409.480000
std     14.57738  11.768446  15727.122334
min    101.00000  20.000000  35452.000000
25%    113.25000  24.250000  57309.750000
50%    125.50000  35.000000  72037.500000
75%    137.75000  46.500000  79512.000000
max    150.00000  54.000000  94722.000000

In [209]:
new_df = df[['emp_id','emp_age','role']]

con = new_df.loc[
    (df['emp_age'] >= 25) & (df['emp_age'] <= 40)
]

con

    emp_id  emp_age                 role
4      105       37    Backend Developer
5      106       37           HR Manager
7      108       35      Sales Executive
9      110       38         HR Executive
10     111       31    Backend Developer
11     112       35  Marketing Executive
12     113       29      Sales Executive
13     114       38   Operations Manager
14     115       27     Digital Marketer
19     120       32    Backend Developer
23     124       26   Software Developer
25     126       37   Operations Manager
26     127       26     Digital Marketer
29     130       30           Accountant
37     138       30           Accountant
38     139       27           HR Manager
39     140       25      Sales Executive
40     141       39  Marketing Executive
48     149       31     Digital Marketer

In [210]:
new_con = con.sort_values('emp_id')
new_con

    emp_id  emp_age                 role
4      105       37    Backend Developer
5      106       37           HR Manager
7      108       35      Sales Executive
9      110       38         HR Executive
10     111       31    Backend Developer
11     112       35  Marketing Executive
12     113       29      Sales Executive
13     114       38   Operations Manager
14     115       27     Digital Marketer
19     120       32    Backend Developer
23     124       26   Software Developer
25     126       37   Operations Manager
26     127       26     Digital Marketer
29     130       30           Accountant
37     138       30           Accountant
38     139       27           HR Manager
39     140       25      Sales Executive
40     141       39  Marketing Executive
48     149       31     Digital Marketer

In [211]:
new_con.tail(3)

    emp_id  emp_age                 role
39     140       25      Sales Executive
40     141       39  Marketing Executive
48     149       31     Digital Marketer

In [212]:
print(df['role'].unique())

HR_df = df.loc[df['role'].str.contains(r"^HR", case=False)]
HR_df

['HR Manager' 'Accountant' 'Operations Manager' 'Digital Marketer'
 'Backend Developer' 'Sales Executive' 'HR Executive'
 'Marketing Executive' 'Financial Analyst' 'Software Developer']

    emp_id  emp_age  emp_salary          role
0      101       54       51725    HR Manager
5      106       37       58915    HR Manager
9      110       38       90494  HR Executive
24     125       53       60584  HR Executive
27     128       21       71888  HR Executive
38     139       27       52013    HR Manager
42     143       47       55523  HR Executive
44     145       22       90794  HR Executive
45     146       52       41061    HR Manager

In [213]:
print("Total HR employee:" , HR_df['emp_id'].count())

Total HR employee: 9

In [214]:
sort_df = df.sort_values(['emp_age','emp_salary'],ascending=[1,0])
sort_df

    emp_id  emp_age  emp_salary                 role
30     131       20       82550      Sales Executive
18     119       20       63187   Software Developer
41     142       20       59500     Digital Marketer
2      103       20       35452   Operations Manager
36     137       21       94427      Sales Executive
22     123       21       76760           Accountant
6      107       21       76159    Backend Developer
27     128       21       71888         HR Executive
44     145       22       90794         HR Executive
34     135       23       73314   Software Developer
1      102       23       38495           Accountant
35     136       24       87428   Software Developer
8      109       24       76155      Sales Executive
39     140       25       63326      Sales Executive
23     124       26       78354   Software Developer
26     127       26       59682     Digital Marketer
14     115       27       94722     Digital Marketer
38     139       27       52013           HR Manager
12     113       29       56879      Sales Executive
37     138       30       84188           Accountant
29     130       30       73700           Accountant
10     111       31       68641    Backend Developer
48     149       31       59727     Digital Marketer
19     120       32       74146    Backend Developer
7      108       35       92864      Sales Executive
11     112       35       48079  Marketing Executive
25     126       37       79898   Operations Manager
4      105       37       72187    Backend Developer
5      106       37       58915           HR Manager
9      110       38       90494         HR Executive
13     114       38       83682   Operations Manager
40     141       39       44396  Marketing Executive
43     144       41       58602           Accountant
46     147       42       82331   Software Developer
3      104       43       82295     Digital Marketer
15     116       45       91041    Financial Analyst
28     129       45       51086   Software Developer
31     132       47       71447  Marketing Executive
42     143       47       55523         HR Executive
17     118       48       68744   Operations Manager
49     150       50       50398  Marketing Executive
20     121       51       75641      Sales Executive
16     117       51       48899      Sales Executive
45     146       52       41061           HR Manager
32     133       53       76100     Digital Marketer
33     134       53       72269    Backend Developer
24     125       53       60584         HR Executive
21     122       53       47678      Sales Executive
47     148       54       73048   Software Developer
0      101       54       51725           HR Manager

In [215]:
sort_df[['emp_id','role','emp_salary']].head()

    emp_id                role  emp_salary
30     131     Sales Executive       82550
18     119  Software Developer       63187
41     142    Digital Marketer       59500
2      103  Operations Manager       35452
36     137     Sales Executive       94427

In [216]:
df['previous_salary'] = df['emp_salary']

dev = ['Software Developer','Backend Developer']
df.loc[df['role'].isin(dev),'new_salary'] = df.loc[df['role'].isin(dev),'emp_salary'] * 1.12
df.loc[~df['role'].isin(dev),'new_salary'] = df.loc[~df['role'].isin(dev),'emp_salary'] * 1.05


df['increase_of_salary'] = df['new_salary'] - df['previous_salary']

df[["role", "previous_salary", "new_salary", "increase_of_salary"]]

                   role  previous_salary  new_salary  increase_of_salary
0            HR Manager            51725    54311.25             2586.25
1            Accountant            38495    40419.75             1924.75
2    Operations Manager            35452    37224.60             1772.60
3      Digital Marketer            82295    86409.75             4114.75
4     Backend Developer            72187    80849.44             8662.44
5            HR Manager            58915    61860.75             2945.75
6     Backend Developer            76159    85298.08             9139.08
7       Sales Executive            92864    97507.20             4643.20
8       Sales Executive            76155    79962.75             3807.75
9          HR Executive            90494    95018.70             4524.70
10    Backend Developer            68641    76877.92             8236.92
11  Marketing Executive            48079    50482.95             2403.95
12      Sales Executive            56879    59722.95             2843.95
13   Operations Manager            83682    87866.10             4184.10
14     Digital Marketer            94722    99458.10             4736.10
15    Financial Analyst            91041    95593.05             4552.05
16      Sales Executive            48899    51343.95             2444.95
17   Operations Manager            68744    72181.20             3437.20
18   Software Developer            63187    70769.44             7582.44
19    Backend Developer            74146    83043.52             8897.52
20      Sales Executive            75641    79423.05             3782.05
21      Sales Executive            47678    50061.90             2383.90
22           Accountant            76760    80598.00             3838.00
23   Software Developer            78354    87756.48             9402.48
24         HR Executive            60584    63613.20             3029.20
25   Operations Manager            79898    83892.90             3994.90
26     Digital Marketer            59682    62666.10             2984.10
27         HR Executive            71888    75482.40             3594.40
28   Software Developer            51086    57216.32             6130.32
29           Accountant            73700    77385.00             3685.00
30      Sales Executive            82550    86677.50             4127.50
31  Marketing Executive            71447    75019.35             3572.35
32     Digital Marketer            76100    79905.00             3805.00
33    Backend Developer            72269    80941.28             8672.28
34   Software Developer            73314    82111.68             8797.68
35   Software Developer            87428    97919.36            10491.36
36      Sales Executive            94427    99148.35             4721.35
37           Accountant            84188    88397.40             4209.40
38           HR Manager            52013    54613.65             2600.65
39      Sales Executive            63326    66492.30             3166.30
40  Marketing Executive            44396    46615.80             2219.80
41     Digital Marketer            59500    62475.00             2975.00
42         HR Executive            55523    58299.15             2776.15
43           Accountant            58602    61532.10             2930.10
44         HR Executive            90794    95333.70             4539.70
45           HR Manager            41061    43114.05             2053.05
46   Software Developer            82331    92210.72             9879.72
47   Software Developer            73048    81813.76             8765.76
48     Digital Marketer            59727    62713.35             2986.35
49  Marketing Executive            50398    52917.90             2519.90