In [2]:
import pandas as pd

df = pd.read_csv('students.csv')
df.head(2)

,StudentID,FullName,Gender,Age,Department,Semester,CGPA,Instructor,Location
0,PH1001,Alif Rahman,Male,19,Physics,1,3.75,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,Female,20,Physics,2,3.60,Ms. Salma,Chattogram

In [3]:
df['Country'] = 'Bangladesh'

In [4]:
df.head(2)

,StudentID,FullName,Gender,Age,Department,Semester,CGPA,Instructor,Location,Country
0,PH1001,Alif Rahman,Male,19,Physics,1,3.75,Mr. Karim,Dhaka,Bangladesh
1,PH1002,Fatima Akhter,Female,20,Physics,2,3.60,Ms. Salma,Chattogram,Bangladesh

In [5]:
df.Age.max()

np.int64(22)

In [7]:
df['New_CGPA'] = df['CGPA'] + (1 - (df['Age'] / 22))
df.head(3)

,StudentID,FullName,Gender,Age,Department,Semester,CGPA,Instructor,Location,Country,New_CGPA
0,PH1001,Alif Rahman,Male,19,Physics,1,3.75,Mr. Karim,Dhaka,Bangladesh,3.886364
1,PH1002,Fatima Akhter,Female,20,Physics,2,3.60,Ms. Salma,Chattogram,Bangladesh,3.690909
2,PH1003,Imran Hossain,Male,21,Physics,3,3.45,Mr. Karim,Dhaka,Bangladesh,3.495455

In [8]:
import numpy as np

In [9]:
df['New Subject'] = np.where(df['CGPA'] > 3.85 , 'A+','A-')
df.head()

,StudentID,FullName,Gender,Age,Department,Semester,CGPA,Instructor,Location,Country,New_CGPA,New Subject
0,PH1001,Alif Rahman,Male,19,Physics,1,3.75,Mr. Karim,Dhaka,Bangladesh,3.886364,A-
1,PH1002,Fatima Akhter,Female,20,Physics,2,3.60,Ms. Salma,Chattogram,Bangladesh,3.690909,A-
2,PH1003,Imran Hossain,Male,21,Physics,3,3.45,Mr. Karim,Dhaka,Bangladesh,3.495455,A-
3,PH1004,Nusrat Jahan,Female,19,Physics,1,3.80,Ms. Salma,Sylhet,Bangladesh,3.936364,A-
4,PH1005,Rafiul Islam,Male,22,Physics,4,3.30,Mr. Karim,Dhaka,Bangladesh,3.300000,A-

In [10]:
# Data Structure Marks 70-এর বেশি হলে True, নাহলে False
df['Passed in DS'] = df['CGPA'] > 3.80

df.head(10)

,StudentID,FullName,Gender,Age,Department,Semester,CGPA,Instructor,Location,Country,New_CGPA,New Subject,Passed in DS
0,PH1001,Alif Rahman,Male,19,Physics,1,3.75,Mr. Karim,Dhaka,Bangladesh,3.886364,A-,False
1,PH1002,Fatima Akhter,Female,20,Physics,2,3.60,Ms. Salma,Chattogram,Bangladesh,3.690909,A-,False
2,PH1003,Imran Hossain,Male,21,Physics,3,3.45,Mr. Karim,Dhaka,Bangladesh,3.495455,A-,False
3,PH1004,Nusrat Jahan,Female,19,Physics,1,3.80,Ms. Salma,Sylhet,Bangladesh,3.936364,A-,False
4,PH1005,Rafiul Islam,Male,22,Physics,4,3.30,Mr. Karim,Dhaka,Bangladesh,3.300000,A-,False
5,PH1006,Sadia Sultana,Female,20,Physics,2,3.55,Ms. Salma,Chattogram,Bangladesh,3.640909,A-,False
6,PH1007,Tanvir Ahmed,Male,21,Physics,3,3.20,Mr. Karim,Dhaka,Bangladesh,3.245455,A-,False
7,PH1008,Umme Kulsum,Female,19,Physics,1,3.90,Ms. Salma,Rajshahi,Bangladesh,4.036364,A+,True
8,PH1009,Wahid Hasan,Male,22,Physics,4,3.10,Mr. Karim,Dhaka,Bangladesh,3.100000,A-,False
9,PH1010,Yasmin Begum,Female,20,Physics,2,3.65,Ms. Salma,Khulna,Bangladesh,3.740909,A-,False