In [2]:
import pandas as pd

data = {
    'Name':['S','A','R','T','Q'],
    'Exam_Score':[89,78,9,37,76],
    'Study_Hours':[6,4,0.2,1,4],
    'Passed':[True,True,False,True,True]
}

df = pd.DataFrame(data)
df

  Name  Exam_Score  Study_Hours  Passed
0    S          89          6.0    True
1    A          78          4.0    True
2    R           9          0.2   False
3    T          37          1.0    True
4    Q          76          4.0    True

In [3]:
df = pd.read_csv('student_performance_prediction.csv')

df

,Student ID,Study Hours per Week,Attendance Rate,Previous Grades,Participation in Extracurricular Activities,Parent Education Level,Passed
0,S00001,12.5,NaN,75.0,Yes,Master,Yes
1,S00002,9.3,95.3,60.6,No,High School,No
2,S00003,13.2,NaN,64.0,No,Associate,No
3,S00004,17.6,76.8,62.4,Yes,Bachelor,No
4,S00005,8.8,89.3,72.7,No,Master,No
...,...,...,...,...,...,...,...
39995,S39996,15.6,93.8,51.4,Yes,Master,No
39996,S39997,11.3,66.4,64.2,No,Doctorate,Yes
39997,S39998,13.1,65.6,38.1,No,Bachelor,No
39998,S39999,14.1,74.9,NaN,Yes,Master,No
39999,S40000,11.8,55.1,68.5,No,Bachelor,Yes

In [4]:
df.head()

,Student ID,Study Hours per Week,Attendance Rate,Previous Grades,Participation in Extracurricular Activities,Parent Education Level,Passed
0,S00001,12.5,NaN,75.0,Yes,Master,Yes
1,S00002,9.3,95.3,60.6,No,High School,No
2,S00003,13.2,NaN,64.0,No,Associate,No
3,S00004,17.6,76.8,62.4,Yes,Bachelor,No
4,S00005,8.8,89.3,72.7,No,Master,No

In [5]:
df.shape

(40000, 7)

In [6]:
df.columns.tolist()

['Student ID',
 'Study Hours per Week',
 'Attendance Rate',
 'Previous Grades',
 'Participation in Extracurricular Activities',
 'Parent Education Level',
 'Passed']

In [7]:
df.index

RangeIndex(start=0, stop=40000, step=1)

In [8]:
df.dtypes

Student ID                                      object
Study Hours per Week                           float64
Attendance Rate                                float64
Previous Grades                                float64
Participation in Extracurricular Activities     object
Parent Education Level                          object
Passed                                          object
dtype: object

In [9]:
df

,Student ID,Study Hours per Week,Attendance Rate,Previous Grades,Participation in Extracurricular Activities,Parent Education Level,Passed
0,S00001,12.5,NaN,75.0,Yes,Master,Yes
1,S00002,9.3,95.3,60.6,No,High School,No
2,S00003,13.2,NaN,64.0,No,Associate,No
3,S00004,17.6,76.8,62.4,Yes,Bachelor,No
4,S00005,8.8,89.3,72.7,No,Master,No
...,...,...,...,...,...,...,...
39995,S39996,15.6,93.8,51.4,Yes,Master,No
39996,S39997,11.3,66.4,64.2,No,Doctorate,Yes
39997,S39998,13.1,65.6,38.1,No,Bachelor,No
39998,S39999,14.1,74.9,NaN,Yes,Master,No
39999,S40000,11.8,55.1,68.5,No,Bachelor,Yes

In [10]:
df['Previous Grades'].head(5)

0    75.0
1    60.6
2    64.0
3    62.4
4    72.7
Name: Previous Grades, dtype: float64

In [11]:
df.Passed.head()

0    Yes
1     No
2     No
3     No
4     No
Name: Passed, dtype: object

In [12]:
df[['Previous Grades','Passed']].head()

   Previous Grades Passed
0             75.0    Yes
1             60.6     No
2             64.0     No
3             62.4     No
4             72.7     No

In [13]:
df.iloc[0]

Student ID                                     S00001
Study Hours per Week                             12.5
Attendance Rate                                   NaN
Previous Grades                                  75.0
Participation in Extracurricular Activities       Yes
Parent Education Level                         Master
Passed                                            Yes
Name: 0, dtype: object

In [14]:
df.iloc[2]

Student ID                                        S00003
Study Hours per Week                                13.2
Attendance Rate                                      NaN
Previous Grades                                     64.0
Participation in Extracurricular Activities           No
Parent Education Level                         Associate
Passed                                                No
Name: 2, dtype: object

In [15]:
df.iloc[0:3]

,Student ID,Study Hours per Week,Attendance Rate,Previous Grades,Participation in Extracurricular Activities,Parent Education Level,Passed
0,S00001,12.5,NaN,75.0,Yes,Master,Yes
1,S00002,9.3,95.3,60.6,No,High School,No
2,S00003,13.2,NaN,64.0,No,Associate,No

In [16]:
df.loc[0]

Student ID                                     S00001
Study Hours per Week                             12.5
Attendance Rate                                   NaN
Previous Grades                                  75.0
Participation in Extracurricular Activities       Yes
Parent Education Level                         Master
Passed                                            Yes
Name: 0, dtype: object

In [17]:
df.loc[0, 'Passed']

'Yes'

In [21]:
df['Grade'] = df['Previous Grades'].apply(
    lambda X: 'A' if X >= 90 else 'B'
)

In [24]:
df[['Grade','Previous Grades']].head(10)

  Grade  Previous Grades
0     B             75.0
1     B             60.6
2     B             64.0
3     B             62.4
4     B             72.7
5     B             69.3
6     A             93.6
7     B             59.2
8     A             91.9
9     B             37.8

In [25]:
df.shape

(40000, 8)

In [27]:
df = df.drop('Grade', axis = 1)
df.shape

(40000, 7)

In [28]:
df.shape

(40000, 7)