In [1]:
import pandas as pd

df = pd.read_csv('students.csv')

df.head(5)

,StudentID,FullName,Gender,Age,Department,Semester,CGPA,Instructor,Location
0,PH1001,Alif Rahman,Male,19,Physics,1,3.75,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,Female,20,Physics,2,3.60,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,Male,21,Physics,3,3.45,Mr. Karim,Dhaka
3,PH1004,Nusrat Jahan,Female,19,Physics,1,3.80,Ms. Salma,Sylhet
4,PH1005,Rafiul Islam,Male,22,Physics,4,3.30,Mr. Karim,Dhaka

In [2]:
df.drop(0, inplace=True)

In [3]:
df.head()

,StudentID,FullName,Gender,Age,Department,Semester,CGPA,Instructor,Location
1,PH1002,Fatima Akhter,Female,20,Physics,2,3.60,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,Male,21,Physics,3,3.45,Mr. Karim,Dhaka
3,PH1004,Nusrat Jahan,Female,19,Physics,1,3.80,Ms. Salma,Sylhet
4,PH1005,Rafiul Islam,Male,22,Physics,4,3.30,Mr. Karim,Dhaka
5,PH1006,Sadia Sultana,Female,20,Physics,2,3.55,Ms. Salma,Chattogram

In [8]:
df.drop('Instructor', axis=1, inplace=True)

df.head()

  StudentID  Gender  Age Department  Semester  CGPA    Location
1    PH1002  Female   20    Physics         2  3.60  Chattogram
2    PH1003    Male   21    Physics         3  3.45       Dhaka
3    PH1004  Female   19    Physics         1  3.80      Sylhet
4    PH1005    Male   22    Physics         4  3.30       Dhaka
5    PH1006  Female   20    Physics         2  3.55  Chattogram

In [9]:
df.loc[1,'Age'] = 22

df.head(3)

  StudentID  Gender  Age Department  Semester  CGPA    Location
1    PH1002  Female   22    Physics         2  3.60  Chattogram
2    PH1003    Male   21    Physics         3  3.45       Dhaka
3    PH1004  Female   19    Physics         1  3.80      Sylhet

In [12]:
df.head(5)

  StudentID  Gender  Age Department  Semester  CGPA    Location
1    PH1002  Female   22    Physics         2  3.80  Chattogram
2    PH1003    Male   21    Physics         3  3.65       Dhaka
3    PH1004  Female   19    Physics         1  3.90      Sylhet
4    PH1005    Male   22    Physics         4  3.30       Dhaka
5    PH1006  Female   20    Physics         2  3.55  Chattogram

In [13]:
df.loc[1:3,'CGPA'] += 0.1

df.head(4)

  StudentID  Gender  Age Department  Semester  CGPA    Location
1    PH1002  Female   22    Physics         2  3.90  Chattogram
2    PH1003    Male   21    Physics         3  3.75       Dhaka
3    PH1004  Female   19    Physics         1  4.00      Sylhet
4    PH1005    Male   22    Physics         4  3.30       Dhaka

In [14]:
for i, series in df.iterrows():
    print(f"{i} : {series}")

1 : StudentID         PH1002
Gender            Female
Age                   22
Department       Physics
Semester               2
CGPA                 3.9
Location      Chattogram
Name: 1, dtype: object
2 : StudentID      PH1003
Gender           Male
Age                21
Department    Physics
Semester            3
CGPA             3.75
Location        Dhaka
Name: 2, dtype: object
3 : StudentID      PH1004
Gender         Female
Age                19
Department    Physics
Semester            1
CGPA              4.0
Location       Sylhet
Name: 3, dtype: object
4 : StudentID      PH1005
Gender           Male
Age                22
Department    Physics
Semester            4
CGPA              3.3
Location        Dhaka
Name: 4, dtype: object
5 : StudentID         PH1006
Gender            Female
Age                   20
Department       Physics
Semester               2
CGPA                3.55
Location      Chattogram
Name: 5, dtype: object
6 : StudentID      PH1007
Gender           Male
Age                21
Department    Physics
Semester            3
CGPA              3.2
Location        Dhaka
Name: 6, dtype: object
7 : StudentID       PH1008
Gender          Female
Age                 19
Department     Physics
Semester             1
CGPA               3.9
Location      Rajshahi
Name: 7, dtype: object
8 : StudentID      PH1009
Gender           Male
Age                22
Department    Physics
Semester            4
CGPA              3.1
Location        Dhaka
Name: 8, dtype: object
9 : StudentID      PH1010
Gender         Female
Age                20
Department    Physics
Semester            2
CGPA             3.65
Location       Khulna
Name: 9, dtype: object
10 : StudentID      PH1011
Gender           Male
Age                21
Department    Physics
Semester            3
CGPA              3.4
Location        Dhaka
Name: 10, dtype: object
11 : StudentID         PH1012
Gender            Female
Age                   19
Department       Physics
Semester               1
CGPA                3.85
Location      Chattogram
Name: 11, dtype: object
12 : StudentID      PH1013
Gender           Male
Age                20
Department    Physics
Semester            2
CGPA             3.25
Location        Dhaka
Name: 12, dtype: object
13 : StudentID      PH1014
Gender         Female
Age                21
Department    Physics
Semester            3
CGPA              3.5
Location       Sylhet
Name: 13, dtype: object
14 : StudentID      PH1015
Gender           Male
Age                22
Department    Physics
Semester            4
CGPA             3.15
Location        Dhaka
Name: 14, dtype: object
15 : StudentID         PH1016
Gender            Female
Age                   19
Department       Physics
Semester               1
CGPA                 3.7
Location      Chattogram
Name: 15, dtype: object
16 : StudentID      PH1017
Gender           Male
Age                20
Department    Physics
Semester            2
CGPA             3.35
Location        Dhaka
Name: 16, dtype: object
17 : StudentID       PH1018
Gender          Female
Age                 21
Department     Physics
Semester             3
CGPA               3.6
Location      Rajshahi
Name: 17, dtype: object
18 : StudentID      PH1019
Gender           Male
Age                22
Department    Physics
Semester            4
CGPA             3.05
Location        Dhaka
Name: 18, dtype: object
19 : StudentID      PH1020
Gender           Male
Age                20
Department    Physics
Semester            2
CGPA             3.45
Location        Dhaka
Name: 19, dtype: object

In [15]:
for i in df.itertuples(index=False):
    print(i)

Pandas(StudentID='PH1002', Gender='Female', Age=22, Department='Physics', Semester=2, CGPA=3.9000000000000004, Location='Chattogram')
Pandas(StudentID='PH1003', Gender='Male', Age=21, Department='Physics', Semester=3, CGPA=3.7500000000000004, Location='Dhaka')
Pandas(StudentID='PH1004', Gender='Female', Age=19, Department='Physics', Semester=1, CGPA=4.0, Location='Sylhet')
Pandas(StudentID='PH1005', Gender='Male', Age=22, Department='Physics', Semester=4, CGPA=3.3, Location='Dhaka')
Pandas(StudentID='PH1006', Gender='Female', Age=20, Department='Physics', Semester=2, CGPA=3.55, Location='Chattogram')
Pandas(StudentID='PH1007', Gender='Male', Age=21, Department='Physics', Semester=3, CGPA=3.2, Location='Dhaka')
Pandas(StudentID='PH1008', Gender='Female', Age=19, Department='Physics', Semester=1, CGPA=3.9, Location='Rajshahi')
Pandas(StudentID='PH1009', Gender='Male', Age=22, Department='Physics', Semester=4, CGPA=3.1, Location='Dhaka')
Pandas(StudentID='PH1010', Gender='Female', Age=20, Department='Physics', Semester=2, CGPA=3.65, Location='Khulna')
Pandas(StudentID='PH1011', Gender='Male', Age=21, Department='Physics', Semester=3, CGPA=3.4, Location='Dhaka')
Pandas(StudentID='PH1012', Gender='Female', Age=19, Department='Physics', Semester=1, CGPA=3.85, Location='Chattogram')
Pandas(StudentID='PH1013', Gender='Male', Age=20, Department='Physics', Semester=2, CGPA=3.25, Location='Dhaka')
Pandas(StudentID='PH1014', Gender='Female', Age=21, Department='Physics', Semester=3, CGPA=3.5, Location='Sylhet')
Pandas(StudentID='PH1015', Gender='Male', Age=22, Department='Physics', Semester=4, CGPA=3.15, Location='Dhaka')
Pandas(StudentID='PH1016', Gender='Female', Age=19, Department='Physics', Semester=1, CGPA=3.7, Location='Chattogram')
Pandas(StudentID='PH1017', Gender='Male', Age=20, Department='Physics', Semester=2, CGPA=3.35, Location='Dhaka')
Pandas(StudentID='PH1018', Gender='Female', Age=21, Department='Physics', Semester=3, CGPA=3.6, Location='Rajshahi')
Pandas(StudentID='PH1019', Gender='Male', Age=22, Department='Physics', Semester=4, CGPA=3.05, Location='Dhaka')
Pandas(StudentID='PH1020', Gender='Male', Age=20, Department='Physics', Semester=2, CGPA=3.45, Location='Dhaka')