In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('student_data.csv')

df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [3]:
famsize = df.loc[df['famsize'] == 'GT3']

In [4]:
famsize

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,4,1,1,1,6,6,5,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,MS,F,18,R,GT3,T,2,2,at_home,other,...,5,3,3,1,3,4,2,10,9,10
386,MS,F,18,R,GT3,T,4,4,teacher,at_home,...,4,4,3,2,2,5,7,6,5,6
387,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,0,7,5,0
389,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,0,6,5,0
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7

In [5]:
df.school.unique()

array(['GP', 'MS'], dtype=object)

In [7]:
df.Fjob.unique()

array(['teacher', 'other', 'services', 'health', 'at_home'], dtype=object)

In [8]:
teacher = df.loc[df['Fjob'] == 'teacher']

teacher

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,4,1,1,1,6,6,5,6
29,GP,M,16,U,GT3,T,4,4,teacher,teacher,...,4,4,5,5,5,5,16,10,12,11
37,GP,M,16,R,GT3,A,4,4,other,teacher,...,2,4,3,1,1,5,7,15,16,15
42,GP,M,15,U,GT3,T,4,4,services,teacher,...,4,3,3,1,1,5,2,19,18,18
49,GP,F,15,U,GT3,T,4,4,services,teacher,...,4,4,4,1,1,3,2,7,7,7
60,GP,F,16,R,GT3,T,4,4,health,teacher,...,2,4,4,2,3,4,6,10,11,11
101,GP,M,16,U,GT3,T,4,4,services,teacher,...,4,4,3,1,1,4,0,16,17,17
110,GP,M,15,U,LE3,A,4,4,teacher,teacher,...,5,5,3,1,1,4,6,18,19,19
115,GP,M,16,U,GT3,T,4,4,teacher,teacher,...,5,4,4,1,2,5,2,15,15,16
116,GP,M,15,U,GT3,T,4,4,other,teacher,...,4,4,3,1,1,2,2,11,13,14
129,GP,M,16,R,GT3,T,4,4,teacher,teacher,...,3,5,5,2,5,4,8,18,18,18
130,GP,F,15,R,GT3,T,3,4,services,teacher,...,4,2,2,2,2,5,0,12,0,0
134,GP,M,15,R,GT3,T,3,4,at_home,teacher,...,5,3,3,1,1,5,0,9,0,0
139,GP,F,15,U,GT3,T,4,4,teacher,teacher,...,4,3,2,1,1,5,0,16,16,15
148,GP,M,16,U,GT3,T,4,4,teacher,teacher,...,3,3,2,2,1,5,0,7,6,0
154,GP,F,17,U,GT3,T,4,4,other,teacher,...,4,2,1,1,1,4,0,11,11,12
196,GP,M,17,U,GT3,T,4,4,services,teacher,...,5,2,3,1,2,5,4,17,15,16
198,GP,F,17,U,GT3,T,4,4,services,teacher,...,4,2,4,2,3,2,24,18,18,18
199,GP,F,16,U,LE3,T,4,4,teacher,teacher,...,4,5,2,1,2,3,0,9,9,10
222,GP,F,16,U,GT3,T,2,3,services,teacher,...,2,3,1,1,1,3,2,16,16,17
232,GP,M,17,U,GT3,T,4,4,teacher,teacher,...,4,5,5,1,3,2,14,11,9,9
287,GP,F,17,U,GT3,T,1,1,services,teacher,...,4,3,3,1,1,3,6,13,12,12
289,GP,M,18,U,LE3,A,4,4,teacher,teacher,...,5,4,3,1,1,2,9,15,13,15
299,GP,M,18,U,LE3,T,4,4,teacher,teacher,...,1,4,2,2,2,1,5,16,15,16
301,GP,M,17,U,LE3,T,4,4,other,teacher,...,4,1,1,2,2,5,0,11,11,10
329,GP,F,17,U,GT3,T,4,4,teacher,teacher,...,4,3,3,1,2,4,4,14,14,14
369,MS,F,18,R,GT3,T,4,4,other,teacher,...,3,2,2,4,2,5,10,14,12,11
380,MS,M,18,U,GT3,T,4,4,teacher,teacher,...,3,2,4,1,4,2,4,15,14,14

In [10]:
teacher_male = df.loc[(df['Fjob'] == 'teacher') & (df['sex'] == 'M')]
teacher_male

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
29,GP,M,16,U,GT3,T,4,4,teacher,teacher,...,4,4,5,5,5,5,16,10,12,11
37,GP,M,16,R,GT3,A,4,4,other,teacher,...,2,4,3,1,1,5,7,15,16,15
42,GP,M,15,U,GT3,T,4,4,services,teacher,...,4,3,3,1,1,5,2,19,18,18
101,GP,M,16,U,GT3,T,4,4,services,teacher,...,4,4,3,1,1,4,0,16,17,17
110,GP,M,15,U,LE3,A,4,4,teacher,teacher,...,5,5,3,1,1,4,6,18,19,19
115,GP,M,16,U,GT3,T,4,4,teacher,teacher,...,5,4,4,1,2,5,2,15,15,16
116,GP,M,15,U,GT3,T,4,4,other,teacher,...,4,4,3,1,1,2,2,11,13,14
129,GP,M,16,R,GT3,T,4,4,teacher,teacher,...,3,5,5,2,5,4,8,18,18,18
134,GP,M,15,R,GT3,T,3,4,at_home,teacher,...,5,3,3,1,1,5,0,9,0,0
148,GP,M,16,U,GT3,T,4,4,teacher,teacher,...,3,3,2,2,1,5,0,7,6,0
196,GP,M,17,U,GT3,T,4,4,services,teacher,...,5,2,3,1,2,5,4,17,15,16
232,GP,M,17,U,GT3,T,4,4,teacher,teacher,...,4,5,5,1,3,2,14,11,9,9
289,GP,M,18,U,LE3,A,4,4,teacher,teacher,...,5,4,3,1,1,2,9,15,13,15
299,GP,M,18,U,LE3,T,4,4,teacher,teacher,...,1,4,2,2,2,1,5,16,15,16
301,GP,M,17,U,LE3,T,4,4,other,teacher,...,4,1,1,2,2,5,0,11,11,10
380,MS,M,18,U,GT3,T,4,4,teacher,teacher,...,3,2,4,1,4,2,4,15,14,14