In [1]:
import pandas as pd

df = pd.read_csv('student_data.csv')

df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [2]:
df.loc[df['Mjob'].str.contains('home')]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
39,GP,F,15,R,GT3,T,2,2,at_home,other,...,4,3,1,1,1,2,8,14,13,13
79,GP,F,16,U,GT3,T,3,4,at_home,other,...,2,4,3,1,2,3,12,5,5,5
86,GP,F,16,U,LE3,T,2,2,at_home,other,...,4,3,4,1,2,2,4,8,7,6
95,GP,F,15,R,GT3,T,1,1,at_home,other,...,3,1,2,1,1,1,2,7,10,10
112,GP,F,16,U,GT3,T,2,2,at_home,other,...,3,1,2,1,1,5,6,10,13,13
120,GP,F,15,U,GT3,T,1,2,at_home,services,...,3,2,3,1,2,1,2,16,15,15
127,GP,F,19,U,GT3,T,0,1,at_home,other,...,3,4,2,1,1,5,2,7,8,9
131,GP,F,15,U,GT3,T,1,1,at_home,other,...,4,3,3,1,2,4,0,8,0,0
134,GP,M,15,R,GT3,T,3,4,at_home,teacher,...,5,3,3,1,1,5,0,9,0,0
136,GP,M,17,R,GT3,T,3,4,at_home,other,...,5,4,5,2,4,5,0,10,0,0
143,GP,F,16,U,LE3,T,1,1,at_home,at_home,...,3,4,4,3,3,1,2,14,14,13
147,GP,F,15,U,GT3,T,1,2,at_home,other,...,4,3,2,1,1,5,2,10,11,11
151,GP,M,16,U,LE3,T,2,1,at_home,other,...,4,4,4,3,5,5,6,12,13,14
155,GP,M,15,R,GT3,T,2,3,at_home,services,...,4,4,4,1,1,1,2,11,8,8
157,GP,F,18,R,GT3,T,1,1,at_home,other,...,5,2,5,1,5,4,6,9,8,10
158,GP,M,16,R,GT3,T,2,2,at_home,other,...,4,2,2,1,2,3,2,17,15,15
160,GP,M,17,R,LE3,T,2,1,at_home,other,...,3,3,2,2,2,5,0,7,6,0
163,GP,M,17,U,GT3,T,1,3,at_home,services,...,5,3,3,1,4,2,2,10,10,10
173,GP,F,16,U,GT3,T,1,3,at_home,services,...,4,3,5,1,1,3,0,8,7,0
189,GP,M,17,R,GT3,T,1,2,at_home,other,...,3,1,3,1,5,3,4,8,9,10
191,GP,F,17,U,GT3,T,1,1,at_home,services,...,5,3,3,1,1,3,0,8,8,9
192,GP,M,17,U,GT3,T,1,2,at_home,services,...,4,4,4,4,5,5,12,7,8,8
205,GP,F,17,U,GT3,T,3,4,at_home,services,...,4,4,3,3,4,5,28,10,9,9
208,GP,F,16,U,GT3,T,1,1,at_home,other,...,4,3,2,1,4,5,6,9,9,10
218,GP,F,17,U,GT3,T,2,3,at_home,other,...,3,3,3,1,4,3,3,7,7,8
219,GP,F,17,U,GT3,T,2,2,at_home,at_home,...,4,3,3,1,1,4,4,9,10,10
220,GP,F,17,R,GT3,T,2,1,at_home,services,...,4,2,5,1,2,5,2,6,6,6
221,GP,F,17,U,GT3,T,1,1,at_home,other,...,4,3,4,1,1,5,0,6,5,0
228,GP,M,18,U,LE3,T,2,1,at_home,other,...,4,3,2,4,5,3,14,10,8,9
235,GP,M,16,U,GT3,T,3,2,at_home,other,...,5,3,3,1,3,2,10,11,9,10
238,GP,F,17,R,GT3,T,2,1,at_home,services,...,2,1,1,1,1,3,2,13,11,11
251,GP,M,16,U,GT3,T,3,3,at_home,other,...,5,3,3,1,3,2,6,7,10,10
264,GP,F,18,U,GT3,T,2,2,at_home,services,...,4,3,3,1,1,3,0,9,10,0
273,GP,M,17,R,GT3,T,1,2,at_home,at_home,...,3,5,2,2,2,1,2,15,14,14
274,GP,F,17,U,GT3,T,2,4,at_home,health,...,4,3,3,1,1,1,2,10,10,10
282,GP,F,18,R,LE3,T,1,1,at_home,other,...,5,2,2,1,1,3,1,12,12,12
286,GP,F,18,U,GT3,T,2,2,at_home,at_home,...,4,3,3,1,2,2,5,18,18,19
309,GP,F,19,U,LE3,T,1,1,at_home,other,...,4,4,3,1,3,3,18,12,10,10
311,GP,F,19,U,GT3,T,2,1,at_home,other,...,3,4,1,1,1,2,20,14,12,13
314,GP,F,19,U,GT3,T,1,1,at_home,health,...,4,1,2,1,1,3,14,15,13,13
318,GP,F,17,R,GT3,T,3,4,at_home,services,...,4,3,4,2,5,5,0,11,11,10
324,GP,F,17,U,LE3,T,0,2,at_home,at_home,...,3,3,3,2,3,2,0,16,15,15
331,GP,F,17,R,GT3,T,2,4,at_home,other,...,4,4,3,1,1,5,7,12,14,14
334,GP,F,18,R,GT3,T,2,2,at_home,other,...,4,4,4,1,1,4,0,10,9,0
343,GP,F,17,U,GT3,A,2,2,at_home,at_home,...,3,3,1,1,2,4,0,9,8,0
344,GP,F,18,U,GT3,T,2,3,at_home,other,...,4,3,3,1,2,3,4,11,10,10
352,MS,M,18,U,LE3,T,1,3,at_home,services,...,4,3,3,2,3,3,7,8,7,8
359,MS,F,18,U,LE3,T,1,1,at_home,services,...,5,3,2,1,1,4,0,18,16,16
360,MS,F,18,R,LE3,A,1,4,at_home,other,...,4,3,4,1,4,5,0,13,13,13
361,MS,M,18,R,LE3,T,1,1,at_home,other,...,4,4,3,2,3,5,2,13,12,12
363,MS,F,17,U,LE3,T,4,4,at_home,at_home,...,2,3,4,1,1,1,0,16,15,15
365,MS,M,18,R,GT3,T,1,3,at_home,other,...,3,3,4,2,4,3,4,10,10,10
368,MS,F,18,U,GT3,T,2,3,at_home,services,...,5,2,3,1,2,4,0,11,10,10
371,MS,M,18,R,LE3,T,1,2,at_home,services,...,4,3,3,2,3,3,3,14,12,12
379,MS,F,17,R,GT3,T,3,1,at_home,other,...,4,5,4,2,3,1,17,10,10,10
385,MS,F,18,R,GT3,T,2,2,at_home,other,...,5,3,3,1,3,4,2,10,9,10

In [3]:
df.shape

(395, 33)

In [6]:
df.head(5)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [7]:
df.loc[df['Mjob'].str.contains('HOME', case=False)]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
39,GP,F,15,R,GT3,T,2,2,at_home,other,...,4,3,1,1,1,2,8,14,13,13
79,GP,F,16,U,GT3,T,3,4,at_home,other,...,2,4,3,1,2,3,12,5,5,5
86,GP,F,16,U,LE3,T,2,2,at_home,other,...,4,3,4,1,2,2,4,8,7,6
95,GP,F,15,R,GT3,T,1,1,at_home,other,...,3,1,2,1,1,1,2,7,10,10
112,GP,F,16,U,GT3,T,2,2,at_home,other,...,3,1,2,1,1,5,6,10,13,13
120,GP,F,15,U,GT3,T,1,2,at_home,services,...,3,2,3,1,2,1,2,16,15,15
127,GP,F,19,U,GT3,T,0,1,at_home,other,...,3,4,2,1,1,5,2,7,8,9
131,GP,F,15,U,GT3,T,1,1,at_home,other,...,4,3,3,1,2,4,0,8,0,0
134,GP,M,15,R,GT3,T,3,4,at_home,teacher,...,5,3,3,1,1,5,0,9,0,0
136,GP,M,17,R,GT3,T,3,4,at_home,other,...,5,4,5,2,4,5,0,10,0,0
143,GP,F,16,U,LE3,T,1,1,at_home,at_home,...,3,4,4,3,3,1,2,14,14,13
147,GP,F,15,U,GT3,T,1,2,at_home,other,...,4,3,2,1,1,5,2,10,11,11
151,GP,M,16,U,LE3,T,2,1,at_home,other,...,4,4,4,3,5,5,6,12,13,14
155,GP,M,15,R,GT3,T,2,3,at_home,services,...,4,4,4,1,1,1,2,11,8,8
157,GP,F,18,R,GT3,T,1,1,at_home,other,...,5,2,5,1,5,4,6,9,8,10
158,GP,M,16,R,GT3,T,2,2,at_home,other,...,4,2,2,1,2,3,2,17,15,15
160,GP,M,17,R,LE3,T,2,1,at_home,other,...,3,3,2,2,2,5,0,7,6,0
163,GP,M,17,U,GT3,T,1,3,at_home,services,...,5,3,3,1,4,2,2,10,10,10
173,GP,F,16,U,GT3,T,1,3,at_home,services,...,4,3,5,1,1,3,0,8,7,0
189,GP,M,17,R,GT3,T,1,2,at_home,other,...,3,1,3,1,5,3,4,8,9,10
191,GP,F,17,U,GT3,T,1,1,at_home,services,...,5,3,3,1,1,3,0,8,8,9
192,GP,M,17,U,GT3,T,1,2,at_home,services,...,4,4,4,4,5,5,12,7,8,8
205,GP,F,17,U,GT3,T,3,4,at_home,services,...,4,4,3,3,4,5,28,10,9,9
208,GP,F,16,U,GT3,T,1,1,at_home,other,...,4,3,2,1,4,5,6,9,9,10
218,GP,F,17,U,GT3,T,2,3,at_home,other,...,3,3,3,1,4,3,3,7,7,8
219,GP,F,17,U,GT3,T,2,2,at_home,at_home,...,4,3,3,1,1,4,4,9,10,10
220,GP,F,17,R,GT3,T,2,1,at_home,services,...,4,2,5,1,2,5,2,6,6,6
221,GP,F,17,U,GT3,T,1,1,at_home,other,...,4,3,4,1,1,5,0,6,5,0
228,GP,M,18,U,LE3,T,2,1,at_home,other,...,4,3,2,4,5,3,14,10,8,9
235,GP,M,16,U,GT3,T,3,2,at_home,other,...,5,3,3,1,3,2,10,11,9,10
238,GP,F,17,R,GT3,T,2,1,at_home,services,...,2,1,1,1,1,3,2,13,11,11
251,GP,M,16,U,GT3,T,3,3,at_home,other,...,5,3,3,1,3,2,6,7,10,10
264,GP,F,18,U,GT3,T,2,2,at_home,services,...,4,3,3,1,1,3,0,9,10,0
273,GP,M,17,R,GT3,T,1,2,at_home,at_home,...,3,5,2,2,2,1,2,15,14,14
274,GP,F,17,U,GT3,T,2,4,at_home,health,...,4,3,3,1,1,1,2,10,10,10
282,GP,F,18,R,LE3,T,1,1,at_home,other,...,5,2,2,1,1,3,1,12,12,12
286,GP,F,18,U,GT3,T,2,2,at_home,at_home,...,4,3,3,1,2,2,5,18,18,19
309,GP,F,19,U,LE3,T,1,1,at_home,other,...,4,4,3,1,3,3,18,12,10,10
311,GP,F,19,U,GT3,T,2,1,at_home,other,...,3,4,1,1,1,2,20,14,12,13
314,GP,F,19,U,GT3,T,1,1,at_home,health,...,4,1,2,1,1,3,14,15,13,13
318,GP,F,17,R,GT3,T,3,4,at_home,services,...,4,3,4,2,5,5,0,11,11,10
324,GP,F,17,U,LE3,T,0,2,at_home,at_home,...,3,3,3,2,3,2,0,16,15,15
331,GP,F,17,R,GT3,T,2,4,at_home,other,...,4,4,3,1,1,5,7,12,14,14
334,GP,F,18,R,GT3,T,2,2,at_home,other,...,4,4,4,1,1,4,0,10,9,0
343,GP,F,17,U,GT3,A,2,2,at_home,at_home,...,3,3,1,1,2,4,0,9,8,0
344,GP,F,18,U,GT3,T,2,3,at_home,other,...,4,3,3,1,2,3,4,11,10,10
352,MS,M,18,U,LE3,T,1,3,at_home,services,...,4,3,3,2,3,3,7,8,7,8
359,MS,F,18,U,LE3,T,1,1,at_home,services,...,5,3,2,1,1,4,0,18,16,16
360,MS,F,18,R,LE3,A,1,4,at_home,other,...,4,3,4,1,4,5,0,13,13,13
361,MS,M,18,R,LE3,T,1,1,at_home,other,...,4,4,3,2,3,5,2,13,12,12
363,MS,F,17,U,LE3,T,4,4,at_home,at_home,...,2,3,4,1,1,1,0,16,15,15
365,MS,M,18,R,GT3,T,1,3,at_home,other,...,3,3,4,2,4,3,4,10,10,10
368,MS,F,18,U,GT3,T,2,3,at_home,services,...,5,2,3,1,2,4,0,11,10,10
371,MS,M,18,R,LE3,T,1,2,at_home,services,...,4,3,3,2,3,3,3,14,12,12
379,MS,F,17,R,GT3,T,3,1,at_home,other,...,4,5,4,2,3,1,17,10,10,10
385,MS,F,18,R,GT3,T,2,2,at_home,other,...,5,3,3,1,3,4,2,10,9,10

In [8]:
df = pd.read_csv('students.csv')
df

,StudentID,FullName,Gender,Age,Department,Semester,CGPA,Instructor,Location
0,PH1001,Alif Rahman,Male,19,Physics,1,3.75,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,Female,20,Physics,2,3.60,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,Male,21,Physics,3,3.45,Mr. Karim,Dhaka
3,PH1004,Nusrat Jahan,Female,19,Physics,1,3.80,Ms. Salma,Sylhet
4,PH1005,Rafiul Islam,Male,22,Physics,4,3.30,Mr. Karim,Dhaka
5,PH1006,Sadia Sultana,Female,20,Physics,2,3.55,Ms. Salma,Chattogram
6,PH1007,Tanvir Ahmed,Male,21,Physics,3,3.20,Mr. Karim,Dhaka
7,PH1008,Umme Kulsum,Female,19,Physics,1,3.90,Ms. Salma,Rajshahi
8,PH1009,Wahid Hasan,Male,22,Physics,4,3.10,Mr. Karim,Dhaka
9,PH1010,Yasmin Begum,Female,20,Physics,2,3.65,Ms. Salma,Khulna
10,PH1011,Zahidul Karim,Male,21,Physics,3,3.40,Mr. Karim,Dhaka
11,PH1012,Anika Tasnim,Female,19,Physics,1,3.85,Ms. Salma,Chattogram
12,PH1013,Belal Hossain,Male,20,Physics,2,3.25,Mr. Karim,Dhaka
13,PH1014,Champa Akter,Female,21,Physics,3,3.50,Ms. Salma,Sylhet
14,PH1015,Delwar Hossain,Male,22,Physics,4,3.15,Mr. Karim,Dhaka
15,PH1016,Esrat Jahan,Female,19,Physics,1,3.70,Ms. Salma,Chattogram
16,PH1017,Farhan Kabir,Male,20,Physics,2,3.35,Mr. Karim,Dhaka
17,PH1018,Gulshan Ara,Female,21,Physics,3,3.60,Ms. Salma,Rajshahi
18,PH1019,Habibur Rahman,Male,22,Physics,4,3.05,Mr. Karim,Dhaka
19,PH1020,Nasir Khan,Male,20,Physics,2,3.45,Ms. Salma,Dhaka

In [9]:
df.loc[df['FullName'].str.contains(r"^A")]

,StudentID,FullName,Gender,Age,Department,Semester,CGPA,Instructor,Location
0,PH1001,Alif Rahman,Male,19,Physics,1,3.75,Mr. Karim,Dhaka
11,PH1012,Anika Tasnim,Female,19,Physics,1,3.85,Ms. Salma,Chattogram

In [10]:
df.loc[df['FullName'].str.contains(r"^A", case=False)]

,StudentID,FullName,Gender,Age,Department,Semester,CGPA,Instructor,Location
0,PH1001,Alif Rahman,Male,19,Physics,1,3.75,Mr. Karim,Dhaka
11,PH1012,Anika Tasnim,Female,19,Physics,1,3.85,Ms. Salma,Chattogram

In [12]:
df.loc[df['FullName'].str.contains(r"im$")]

,StudentID,FullName,Gender,Age,Department,Semester,CGPA,Instructor,Location
10,PH1011,Zahidul Karim,Male,21,Physics,3,3.40,Mr. Karim,Dhaka
11,PH1012,Anika Tasnim,Female,19,Physics,1,3.85,Ms. Salma,Chattogram

In [16]:
df.loc[df['FullName'].str.contains(r"^[AEIOU]")]

,StudentID,FullName,Gender,Age,Department,Semester,CGPA,Instructor,Location
0,PH1001,Alif Rahman,Male,19,Physics,1,3.75,Mr. Karim,Dhaka
2,PH1003,Imran Hossain,Male,21,Physics,3,3.45,Mr. Karim,Dhaka
7,PH1008,Umme Kulsum,Female,19,Physics,1,3.90,Ms. Salma,Rajshahi
11,PH1012,Anika Tasnim,Female,19,Physics,1,3.85,Ms. Salma,Chattogram
15,PH1016,Esrat Jahan,Female,19,Physics,1,3.70,Ms. Salma,Chattogram

In [18]:
df.loc[df['FullName'].str.contains(r"u$")]

Empty DataFrame
Columns: [StudentID, FullName, Gender, Age, Department, Semester, CGPA, Instructor, Location]
Index: []

In [27]:
df.loc[df['FullName'].str.contains(r"^A|m$")]

,StudentID,FullName,Gender,Age,Department,Semester,CGPA,Instructor,Location
0,PH1001,Alif Rahman,Male,19,Physics,1,3.75,Mr. Karim,Dhaka
4,PH1005,Rafiul Islam,Male,22,Physics,4,3.30,Mr. Karim,Dhaka
7,PH1008,Umme Kulsum,Female,19,Physics,1,3.90,Ms. Salma,Rajshahi
9,PH1010,Yasmin Begum,Female,20,Physics,2,3.65,Ms. Salma,Khulna
10,PH1011,Zahidul Karim,Male,21,Physics,3,3.40,Mr. Karim,Dhaka
11,PH1012,Anika Tasnim,Female,19,Physics,1,3.85,Ms. Salma,Chattogram