In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('students.csv')

df.head(5)

,StudentID,FullName,Gender,Age,Department,Semester,CGPA,Instructor,Location
0,PH1001,Alif Rahman,Male,19,Physics,1,3.75,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,Female,20,Physics,2,3.60,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,Male,21,Physics,3,3.45,Mr. Karim,Dhaka
3,PH1004,Nusrat Jahan,Female,19,Physics,1,3.80,Ms. Salma,Sylhet
4,PH1005,Rafiul Islam,Male,22,Physics,4,3.30,Mr. Karim,Dhaka

In [3]:
copy = df.sort_values('CGPA')

copy

,StudentID,FullName,Gender,Age,Department,Semester,CGPA,Instructor,Location
18,PH1019,Habibur Rahman,Male,22,Physics,4,3.05,Mr. Karim,Dhaka
8,PH1009,Wahid Hasan,Male,22,Physics,4,3.10,Mr. Karim,Dhaka
14,PH1015,Delwar Hossain,Male,22,Physics,4,3.15,Mr. Karim,Dhaka
6,PH1007,Tanvir Ahmed,Male,21,Physics,3,3.20,Mr. Karim,Dhaka
12,PH1013,Belal Hossain,Male,20,Physics,2,3.25,Mr. Karim,Dhaka
4,PH1005,Rafiul Islam,Male,22,Physics,4,3.30,Mr. Karim,Dhaka
16,PH1017,Farhan Kabir,Male,20,Physics,2,3.35,Mr. Karim,Dhaka
10,PH1011,Zahidul Karim,Male,21,Physics,3,3.40,Mr. Karim,Dhaka
2,PH1003,Imran Hossain,Male,21,Physics,3,3.45,Mr. Karim,Dhaka
19,PH1020,Nasir Khan,Male,20,Physics,2,3.45,Ms. Salma,Dhaka
13,PH1014,Champa Akter,Female,21,Physics,3,3.50,Ms. Salma,Sylhet
5,PH1006,Sadia Sultana,Female,20,Physics,2,3.55,Ms. Salma,Chattogram
17,PH1018,Gulshan Ara,Female,21,Physics,3,3.60,Ms. Salma,Rajshahi
1,PH1002,Fatima Akhter,Female,20,Physics,2,3.60,Ms. Salma,Chattogram
9,PH1010,Yasmin Begum,Female,20,Physics,2,3.65,Ms. Salma,Khulna
15,PH1016,Esrat Jahan,Female,19,Physics,1,3.70,Ms. Salma,Chattogram
0,PH1001,Alif Rahman,Male,19,Physics,1,3.75,Mr. Karim,Dhaka
3,PH1004,Nusrat Jahan,Female,19,Physics,1,3.80,Ms. Salma,Sylhet
11,PH1012,Anika Tasnim,Female,19,Physics,1,3.85,Ms. Salma,Chattogram
7,PH1008,Umme Kulsum,Female,19,Physics,1,3.90,Ms. Salma,Rajshahi

In [5]:
copy = df.sort_values(['CGPA'],ascending=False)

copy

,StudentID,FullName,Gender,Age,Department,Semester,CGPA,Instructor,Location
7,PH1008,Umme Kulsum,Female,19,Physics,1,3.90,Ms. Salma,Rajshahi
11,PH1012,Anika Tasnim,Female,19,Physics,1,3.85,Ms. Salma,Chattogram
3,PH1004,Nusrat Jahan,Female,19,Physics,1,3.80,Ms. Salma,Sylhet
0,PH1001,Alif Rahman,Male,19,Physics,1,3.75,Mr. Karim,Dhaka
15,PH1016,Esrat Jahan,Female,19,Physics,1,3.70,Ms. Salma,Chattogram
9,PH1010,Yasmin Begum,Female,20,Physics,2,3.65,Ms. Salma,Khulna
17,PH1018,Gulshan Ara,Female,21,Physics,3,3.60,Ms. Salma,Rajshahi
1,PH1002,Fatima Akhter,Female,20,Physics,2,3.60,Ms. Salma,Chattogram
5,PH1006,Sadia Sultana,Female,20,Physics,2,3.55,Ms. Salma,Chattogram
13,PH1014,Champa Akter,Female,21,Physics,3,3.50,Ms. Salma,Sylhet
2,PH1003,Imran Hossain,Male,21,Physics,3,3.45,Mr. Karim,Dhaka
19,PH1020,Nasir Khan,Male,20,Physics,2,3.45,Ms. Salma,Dhaka
10,PH1011,Zahidul Karim,Male,21,Physics,3,3.40,Mr. Karim,Dhaka
16,PH1017,Farhan Kabir,Male,20,Physics,2,3.35,Mr. Karim,Dhaka
4,PH1005,Rafiul Islam,Male,22,Physics,4,3.30,Mr. Karim,Dhaka
12,PH1013,Belal Hossain,Male,20,Physics,2,3.25,Mr. Karim,Dhaka
6,PH1007,Tanvir Ahmed,Male,21,Physics,3,3.20,Mr. Karim,Dhaka
14,PH1015,Delwar Hossain,Male,22,Physics,4,3.15,Mr. Karim,Dhaka
8,PH1009,Wahid Hasan,Male,22,Physics,4,3.10,Mr. Karim,Dhaka
18,PH1019,Habibur Rahman,Male,22,Physics,4,3.05,Mr. Karim,Dhaka

In [6]:
copy = df.sort_values(['CGPA','StudentID'],ascending=False)
copy

,StudentID,FullName,Gender,Age,Department,Semester,CGPA,Instructor,Location
7,PH1008,Umme Kulsum,Female,19,Physics,1,3.90,Ms. Salma,Rajshahi
11,PH1012,Anika Tasnim,Female,19,Physics,1,3.85,Ms. Salma,Chattogram
3,PH1004,Nusrat Jahan,Female,19,Physics,1,3.80,Ms. Salma,Sylhet
0,PH1001,Alif Rahman,Male,19,Physics,1,3.75,Mr. Karim,Dhaka
15,PH1016,Esrat Jahan,Female,19,Physics,1,3.70,Ms. Salma,Chattogram
9,PH1010,Yasmin Begum,Female,20,Physics,2,3.65,Ms. Salma,Khulna
17,PH1018,Gulshan Ara,Female,21,Physics,3,3.60,Ms. Salma,Rajshahi
1,PH1002,Fatima Akhter,Female,20,Physics,2,3.60,Ms. Salma,Chattogram
5,PH1006,Sadia Sultana,Female,20,Physics,2,3.55,Ms. Salma,Chattogram
13,PH1014,Champa Akter,Female,21,Physics,3,3.50,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,Male,20,Physics,2,3.45,Ms. Salma,Dhaka
2,PH1003,Imran Hossain,Male,21,Physics,3,3.45,Mr. Karim,Dhaka
10,PH1011,Zahidul Karim,Male,21,Physics,3,3.40,Mr. Karim,Dhaka
16,PH1017,Farhan Kabir,Male,20,Physics,2,3.35,Mr. Karim,Dhaka
4,PH1005,Rafiul Islam,Male,22,Physics,4,3.30,Mr. Karim,Dhaka
12,PH1013,Belal Hossain,Male,20,Physics,2,3.25,Mr. Karim,Dhaka
6,PH1007,Tanvir Ahmed,Male,21,Physics,3,3.20,Mr. Karim,Dhaka
14,PH1015,Delwar Hossain,Male,22,Physics,4,3.15,Mr. Karim,Dhaka
8,PH1009,Wahid Hasan,Male,22,Physics,4,3.10,Mr. Karim,Dhaka
18,PH1019,Habibur Rahman,Male,22,Physics,4,3.05,Mr. Karim,Dhaka

In [7]:
copy = df.sort_values(['CGPA','StudentID'], ascending = [0, 1])
copy

,StudentID,FullName,Gender,Age,Department,Semester,CGPA,Instructor,Location
7,PH1008,Umme Kulsum,Female,19,Physics,1,3.90,Ms. Salma,Rajshahi
11,PH1012,Anika Tasnim,Female,19,Physics,1,3.85,Ms. Salma,Chattogram
3,PH1004,Nusrat Jahan,Female,19,Physics,1,3.80,Ms. Salma,Sylhet
0,PH1001,Alif Rahman,Male,19,Physics,1,3.75,Mr. Karim,Dhaka
15,PH1016,Esrat Jahan,Female,19,Physics,1,3.70,Ms. Salma,Chattogram
9,PH1010,Yasmin Begum,Female,20,Physics,2,3.65,Ms. Salma,Khulna
1,PH1002,Fatima Akhter,Female,20,Physics,2,3.60,Ms. Salma,Chattogram
17,PH1018,Gulshan Ara,Female,21,Physics,3,3.60,Ms. Salma,Rajshahi
5,PH1006,Sadia Sultana,Female,20,Physics,2,3.55,Ms. Salma,Chattogram
13,PH1014,Champa Akter,Female,21,Physics,3,3.50,Ms. Salma,Sylhet
2,PH1003,Imran Hossain,Male,21,Physics,3,3.45,Mr. Karim,Dhaka
19,PH1020,Nasir Khan,Male,20,Physics,2,3.45,Ms. Salma,Dhaka
10,PH1011,Zahidul Karim,Male,21,Physics,3,3.40,Mr. Karim,Dhaka
16,PH1017,Farhan Kabir,Male,20,Physics,2,3.35,Mr. Karim,Dhaka
4,PH1005,Rafiul Islam,Male,22,Physics,4,3.30,Mr. Karim,Dhaka
12,PH1013,Belal Hossain,Male,20,Physics,2,3.25,Mr. Karim,Dhaka
6,PH1007,Tanvir Ahmed,Male,21,Physics,3,3.20,Mr. Karim,Dhaka
14,PH1015,Delwar Hossain,Male,22,Physics,4,3.15,Mr. Karim,Dhaka
8,PH1009,Wahid Hasan,Male,22,Physics,4,3.10,Mr. Karim,Dhaka
18,PH1019,Habibur Rahman,Male,22,Physics,4,3.05,Mr. Karim,Dhaka