In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [5, np.nan, np.nan, None, 10],
    'C': ['a', 'b', 'c', None, 'e']
})
                   
print(df)

     A     B     C
0  1.0   5.0     a
1  2.0   NaN     b
2  NaN   NaN     c
3  4.0   NaN  None
4  5.0  10.0     e

In [2]:
df_filled = df.fillna({
    'A':0,
    'B':99,
    'C':'Unknown'
})

df_filled

     A     B        C
0  1.0   5.0        a
1  2.0  99.0        b
2  0.0  99.0        c
3  4.0  99.0  Unknown
4  5.0  10.0        e

In [4]:
df_fill_B = df.copy()

df_fill_B

     A     B     C
0  1.0   5.0     a
1  2.0   NaN     b
2  NaN   NaN     c
3  4.0   NaN  None
4  5.0  10.0     e

In [5]:
df_fill_B['B'] = df_fill_B['B'].ffill()
df_fill_B

     A     B     C
0  1.0   5.0     a
1  2.0   5.0     b
2  NaN   5.0     c
3  4.0   5.0  None
4  5.0  10.0     e

In [8]:
def fill_missing(df):
    df_copy = df.copy()

    for column in df_copy.columns:
        if df_copy[column].dtype in ['float64','int64']:
            df_copy[column] = df[column].fillna(df_copy[column].mean())
        else:
            df_copy[column] = df_copy[column].fillna('Unknown')
        
    return df_copy

df_custom = fill_missing(df)
df_custom

     A     B        C
0  1.0   5.0        a
1  2.0   7.5        b
2  3.0   7.5        c
3  4.0   7.5  Unknown
4  5.0  10.0        e

In [9]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [5, np.nan, np.nan, None, 10],
    'C': ['a', 'b', 'c', None, 'e']
})
                   
print(df)

     A     B     C
0  1.0   5.0     a
1  2.0   NaN     b
2  NaN   NaN     c
3  4.0   NaN  None
4  5.0  10.0     e

In [15]:
# Drop rows where column A has missing values
df_clean_based_A = df.dropna(subset=['A'])
print(df_clean_based_A)



# Drop rows with less than 2 non-null values
df_clean_based_2 = df.dropna(thresh=2)
print(df_clean_based_2)


# Drop rows where both Column A and Column B has missing values
df_clean_based_AB = df.dropna(subset=['A', 'B'], how='all')
print(df_clean_based_AB)

     A     B     C
0  1.0   5.0     a
1  2.0   NaN     b
3  4.0   NaN  None
4  5.0  10.0     e
     A     B  C
0  1.0   5.0  a
1  2.0   NaN  b
4  5.0  10.0  e
     A     B     C
0  1.0   5.0     a
1  2.0   NaN     b
3  4.0   NaN  None
4  5.0  10.0     e

In [16]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Category': ['A', 'B', 'A', 'B', 'A', 'B'],
    'Value1': [10, 20, 30, 40, 50, 60],
    'Value2': [100, 200, 300, 400, 500, 600]
})

df

  Category  Value1  Value2
0        A      10     100
1        B      20     200
2        A      30     300
3        B      40     400
4        A      50     500
5        B      60     600

In [19]:
df.groupby('Category')['Value1'].mean()

Category
A    30.0
B    40.0
Name: Value1, dtype: float64

In [20]:
df.groupby('Category')['Value2'].max()

Category
A    500
B    600
Name: Value2, dtype: int64

In [21]:
df.groupby('Category')['Value2'].min()

Category
A    100
B    200
Name: Value2, dtype: int64