In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import TargetEncoder

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import MaxAbsScaler

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

from sklearn.model_selection import train_test_split, GridSearchCV

from sklearn.linear_model import LinearRegression, SGDRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [3]:
df = pd.read_csv('mushrooms.csv')
df.head()

  class cap-shape cap-surface  ... spore-print-color population habitat
0     p         x           s  ...                 k          s       u
1     e         x           s  ...                 n          n       g
2     e         b           s  ...                 n          n       m
3     p         x           y  ...                 k          s       u
4     e         x           s  ...                 n          a       g

[5 rows x 23 columns]

In [4]:
df.shape

(8124, 23)

In [5]:
df['class'].value_counts()

class
e    4208
p    3916
Name: count, dtype: int64

In [6]:
df['class'] = df['class'].map({'e': 0, 'p': 1})

In [11]:
df

      class cap-shape cap-surface  ... spore-print-color population habitat
0         1         x           s  ...                 k          s       u
1         0         x           s  ...                 n          n       g
2         0         b           s  ...                 n          n       m
3         1         x           y  ...                 k          s       u
4         0         x           s  ...                 n          a       g
...     ...       ...         ...  ...               ...        ...     ...
8119      0         k           s  ...                 b          c       l
8120      0         x           s  ...                 b          v       l
8121      0         f           s  ...                 b          c       l
8122      1         k           y  ...                 w          v       l
8123      0         x           s  ...                 o          c       l

[8124 rows x 23 columns]

In [8]:
cat_value = df.select_dtypes(include='object').columns

In [9]:
cat_value

Index(['cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')

In [10]:
df[cat_value].value_counts()

cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  gill-spacing  gill-size  gill-color  stalk-shape  stalk-root  stalk-surface-above-ring  stalk-surface-below-ring  stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  spore-print-color  population  habitat
b          f            g          f        n     f                w             b          g           e            ?           k                         k                         w                       w                       p          w           t            p          w                  n           g          1
x          f            w          f        n     f                w             b          p           e            ?           k                         s                         w                       w                       p          w           t            p          w                  s           g          1
                                                                                                        t            e           s                         f                         w                       w                       p          w           o            e          k                  a           g          1
                                                                                                                                 f                         s                         w                       w                       p          w           o            e          n                  s           g          1
                                                                                                                                                                                                                                                                                                       a           g          1
                                                                                                                                                                                                                                                                                                                             ..
f          y            g          f        f     f                c             b          h           e            b           k                         k                         n                       p                       p          w           o            l          h                  v           p          1
                                                                                                                                                                                                                                                                                                                   g          1
                                                                                                                                                                                                                                                                                                                   d          1
                                                                                                                                                                                                             n                       p          w           o            l          h                  y           p          1
x          y            y          t        l     f                c             b          w           e            r           s                         y                         w                       w                       p          w           o            p          n                  y           p          1
Name: count, Length: 8124, dtype: int64

In [12]:
X = df.drop(columns='class')
y = df['class']

X

     cap-shape cap-surface cap-color  ... spore-print-color population habitat
0            x           s         n  ...                 k          s       u
1            x           s         y  ...                 n          n       g
2            b           s         w  ...                 n          n       m
3            x           y         w  ...                 k          s       u
4            x           s         g  ...                 n          a       g
...        ...         ...       ...  ...               ...        ...     ...
8119         k           s         n  ...                 b          c       l
8120         x           s         n  ...                 b          v       l
8121         f           s         n  ...                 b          c       l
8122         k           y         n  ...                 w          v       l
8123         x           s         n  ...                 o          c       l

[8124 rows x 22 columns]

In [13]:
y

0       1
1       0
2       0
3       1
4       0
       ..
8119    0
8120    0
8121    0
8122    1
8123    0
Name: class, Length: 8124, dtype: int64

In [14]:
X.isnull().sum()

cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [16]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((6499, 22), (1625, 22), (6499,), (1625,))

In [18]:
transformer = ColumnTransformer(transformers=[
    ('encoder', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), cat_value)
])

pipeline = Pipeline(steps=[
    ('preprocessor', transformer),
    ('classifier', DecisionTreeClassifier(random_state=42))
])

param_grid = {
    'classifier__max_depth': [None, 5, 10, 15, 20],
    'classifier__min_samples_split': [5, 10, 20],
    'classifier__min_samples_leaf': [3, 4, 5],
    'classifier__criterion': ['gini', 'entropy'],
    'classifier__class_weight': [None, 'balanced'],
    'classifier__max_features': ['sqrt', 'log2'],
    'classifier__ccp_alpha': [0.01, 0.1, 1.0]
}

grid_search = GridSearchCV(
    estimator = pipeline,
    param_grid = param_grid,
    scoring = 'accuracy',
    cv = 7,
    n_jobs = -1,
    verbose = 1
)

grid_search.fit(X_train, y_train)
grid_search

Fitting 7 folds for each of 1080 candidates, totalling 7560 fits

GridSearchCV(cv=7,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('encoder',
                                                                         OneHotEncoder(handle_unknown='ignore',
                                                                                       sparse_output=False),
                                                                         Index(['cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface...
                                        DecisionTreeClassifier(random_state=42))]),
             n_jobs=-1,
             param_grid={'classifier__ccp_alpha': [0.01, 0.1, 1.0],
                         'classifier__class_weight': [None, 'balanced'],
                         'classifier__criterion': ['gini', 'entropy'],
                         'classifier__max_depth': [None, 5, 10, 15, 20],
                         'classifier__max_features': ['sqrt', 'log2'],
                         'classifier__min_samples_leaf': [3, 4, 5],
                         'classifier__min_samples_split': [5, 10, 20]},
             scoring='accuracy', verbose=1)

In [19]:
grid_search.best_params_

{'classifier__ccp_alpha': 0.01,
 'classifier__class_weight': None,
 'classifier__criterion': 'entropy',
 'classifier__max_depth': None,
 'classifier__max_features': 'sqrt',
 'classifier__min_samples_leaf': 3,
 'classifier__min_samples_split': 20}

In [20]:
grid_search.best_score_

0.9947679983243808

In [21]:
best_model = grid_search.best_estimator_
best_model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('encoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  Index(['cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object'))])),
                ('classifier',
                 DecisionTreeClassifier(ccp_alpha=0.01, criterion='entropy',
                                        max_features='sqrt', min_samples_leaf=3,
                                        min_samples_split=20,
                                        random_state=42))])

In [22]:
y_pred = best_model.predict(X_test)

In [23]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9944615384615385

In [24]:
transformer2 = ColumnTransformer(transformers=[
    ('encoder', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), cat_value)
])

pipeline2 = Pipeline(steps=[
    ('preprocessor', transformer2),
    ('classifier', SVC())
])

param_grid2 = [

    {
        'classifier__kernel': ['linear'],
        'classifier__C': [0.1,1,10],
        'classifier__class_weight': [None,'balanced'],
        'classifier__tol':[0.01,0.1]
    },

    {
        'classifier__kernel': ['rbf'],
        'classifier__C':[0.1,1,10],
        'classifier__gamma':['scale','auto',0.01,0.1],
        'classifier__class_weight':[None,'balanced'],
        'classifier__tol':[0.01,0.1]
    },

    {
        'classifier__kernel':['poly'],
        'classifier__C':[0.1,1,10],
        'classifier__degree':[2,3,4],
        'classifier__gamma':['scale','auto',0.01,0.1],
        'classifier__class_weight':[None,'balanced'],
        'classifier__tol':[0.01,0.1]
    },

    {
        'classifier__kernel':['sigmoid'],
        'classifier__C':[0.1,1,10],
        'classifier__gamma':['scale','auto',0.01,0.1],
        'classifier__class_weight':[None,'balanced'],
        'classifier__tol':[0.01,0.1]
    }

]

grid_search2 = GridSearchCV(
    estimator = pipeline2,
    param_grid = param_grid2,
    scoring = 'accuracy',
    cv = 7,
    n_jobs = -1,
    verbose = 1
)

grid_search2.fit(X_train, y_train)
grid_search2

Fitting 7 folds for each of 252 candidates, totalling 1764 fits

GridSearchCV(cv=7,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('encoder',
                                                                         OneHotEncoder(handle_unknown='ignore',
                                                                                       sparse_output=False),
                                                                         Index(['cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface...
                          'classifier__class_weight': [None, 'balanced'],
                          'classifier__degree': [2, 3, 4],
                          'classifier__gamma': ['scale', 'auto', 0.01, 0.1],
                          'classifier__kernel': ['poly'],
                          'classifier__tol': [0.01, 0.1]},
                         {'classifier__C': [0.1, 1, 10],
                          'classifier__class_weight': [None, 'balanced'],
                          'classifier__gamma': ['scale', 'auto', 0.01, 0.1],
                          'classifier__kernel': ['sigmoid'],
                          'classifier__tol': [0.01, 0.1]}],
             scoring='accuracy', verbose=1)

In [29]:
grid_search2.best_params_

{'classifier__C': 1,
 'classifier__class_weight': None,
 'classifier__kernel': 'linear',
 'classifier__tol': 0.01}

In [30]:
grid_search2.best_score_

1.0

In [32]:
best_model2 = grid_search2.best_estimator_
best_model2

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('encoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  Index(['cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object'))])),
                ('classifier', SVC(C=1, kernel='linear', tol=0.01))])

In [33]:
y_pred = best_model2.predict(X_test)

In [34]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

1.0